// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/PMsgWelfareReturn.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sw {

  /// <summary>Holder for reflection information generated from protos/PMsgWelfareReturn.proto</summary>
  public static partial class PMsgWelfareReturnReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/PMsgWelfareReturn.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PMsgWelfareReturnReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5wcm90b3MvUE1zZ1dlbGZhcmVSZXR1cm4ucHJvdG8SAnN3IjAKG1BNc2dX",
            "ZWxmYXJlUmV0dXJuUXVlcnlJbmZvQxIRCgluUmVzZXJ2ZWQYASABKAUiMAoN",
            "RmV0Y2hUaW1lSW5mbxIQCgh1bllZTU1ERBgBIAEoDRINCgV1bkRheRgCIAEo",
            "DSKHAQobUE1zZ1dlbGZhcmVSZXR1cm5RdWVyeUluZm9TEhMKC3VuRmV0Y2hJ",
            "bmZvGAEgASgNEhMKC3VuSW5mb0NvdW50GAIgASgNEikKDmNGZXRjaFRpbWVJ",
            "bmZvGAMgAygLMhEuc3cuRmV0Y2hUaW1lSW5mbxITCgt1bkVycm9yQ29kZRhj",
            "IAEoDSIuCh1QTXNnV2VsZmFyZVJldHVybkZldGNoUmV3YXJkQxINCgV1bkRh",
            "eRgBIAEoDSJJCh1QTXNnV2VsZmFyZVJldHVybkZldGNoUmV3YXJkUxITCgt1",
            "bkZldGNoSW5mbxgBIAEoDRITCgt1bkVycm9yQ29kZRhjIAEoDWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgWelfareReturnQueryInfoC), global::Sw.PMsgWelfareReturnQueryInfoC.Parser, new[]{ "NReserved" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.FetchTimeInfo), global::Sw.FetchTimeInfo.Parser, new[]{ "UnYYMMDD", "UnDay" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgWelfareReturnQueryInfoS), global::Sw.PMsgWelfareReturnQueryInfoS.Parser, new[]{ "UnFetchInfo", "UnInfoCount", "CFetchTimeInfo", "UnErrorCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgWelfareReturnFetchRewardC), global::Sw.PMsgWelfareReturnFetchRewardC.Parser, new[]{ "UnDay" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgWelfareReturnFetchRewardS), global::Sw.PMsgWelfareReturnFetchRewardS.Parser, new[]{ "UnFetchInfo", "UnErrorCode" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 客户端：查询角色领取回归礼包奖励信息请求
  /// _MSG_WELFARE_RETURN_QUERY_INFO_C
  /// </summary>
  public sealed partial class PMsgWelfareReturnQueryInfoC : pb::IMessage<PMsgWelfareReturnQueryInfoC> {
    private static readonly pb::MessageParser<PMsgWelfareReturnQueryInfoC> _parser = new pb::MessageParser<PMsgWelfareReturnQueryInfoC>(() => new PMsgWelfareReturnQueryInfoC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgWelfareReturnQueryInfoC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgWelfareReturnReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnQueryInfoC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnQueryInfoC(PMsgWelfareReturnQueryInfoC other) : this() {
      nReserved_ = other.nReserved_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnQueryInfoC Clone() {
      return new PMsgWelfareReturnQueryInfoC(this);
    }

    /// <summary>Field number for the "nReserved" field.</summary>
    public const int NReservedFieldNumber = 1;
    private int nReserved_;
    /// <summary>
    /// 保留字段
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NReserved {
      get { return nReserved_; }
      set {
        nReserved_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgWelfareReturnQueryInfoC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgWelfareReturnQueryInfoC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NReserved != other.NReserved) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NReserved != 0) hash ^= NReserved.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NReserved != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(NReserved);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NReserved != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NReserved);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgWelfareReturnQueryInfoC other) {
      if (other == null) {
        return;
      }
      if (other.NReserved != 0) {
        NReserved = other.NReserved;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            NReserved = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 领取时间对应天数
  /// </summary>
  public sealed partial class FetchTimeInfo : pb::IMessage<FetchTimeInfo> {
    private static readonly pb::MessageParser<FetchTimeInfo> _parser = new pb::MessageParser<FetchTimeInfo>(() => new FetchTimeInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FetchTimeInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgWelfareReturnReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchTimeInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchTimeInfo(FetchTimeInfo other) : this() {
      unYYMMDD_ = other.unYYMMDD_;
      unDay_ = other.unDay_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchTimeInfo Clone() {
      return new FetchTimeInfo(this);
    }

    /// <summary>Field number for the "unYYMMDD" field.</summary>
    public const int UnYYMMDDFieldNumber = 1;
    private uint unYYMMDD_;
    /// <summary>
    /// 日期
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnYYMMDD {
      get { return unYYMMDD_; }
      set {
        unYYMMDD_ = value;
      }
    }

    /// <summary>Field number for the "unDay" field.</summary>
    public const int UnDayFieldNumber = 2;
    private uint unDay_;
    /// <summary>
    /// 天数(也就是礼包序号)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnDay {
      get { return unDay_; }
      set {
        unDay_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FetchTimeInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FetchTimeInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnYYMMDD != other.UnYYMMDD) return false;
      if (UnDay != other.UnDay) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnYYMMDD != 0) hash ^= UnYYMMDD.GetHashCode();
      if (UnDay != 0) hash ^= UnDay.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnYYMMDD != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UnYYMMDD);
      }
      if (UnDay != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(UnDay);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnYYMMDD != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnYYMMDD);
      }
      if (UnDay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnDay);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FetchTimeInfo other) {
      if (other == null) {
        return;
      }
      if (other.UnYYMMDD != 0) {
        UnYYMMDD = other.UnYYMMDD;
      }
      if (other.UnDay != 0) {
        UnDay = other.UnDay;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnYYMMDD = input.ReadUInt32();
            break;
          }
          case 16: {
            UnDay = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务端：查询角色领取回归礼包奖励信息请求回复
  /// _MSG_WELFARE_RETURN_QUERY_INFO_S
  /// </summary>
  public sealed partial class PMsgWelfareReturnQueryInfoS : pb::IMessage<PMsgWelfareReturnQueryInfoS> {
    private static readonly pb::MessageParser<PMsgWelfareReturnQueryInfoS> _parser = new pb::MessageParser<PMsgWelfareReturnQueryInfoS>(() => new PMsgWelfareReturnQueryInfoS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgWelfareReturnQueryInfoS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgWelfareReturnReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnQueryInfoS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnQueryInfoS(PMsgWelfareReturnQueryInfoS other) : this() {
      unFetchInfo_ = other.unFetchInfo_;
      unInfoCount_ = other.unInfoCount_;
      cFetchTimeInfo_ = other.cFetchTimeInfo_.Clone();
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnQueryInfoS Clone() {
      return new PMsgWelfareReturnQueryInfoS(this);
    }

    /// <summary>Field number for the "unFetchInfo" field.</summary>
    public const int UnFetchInfoFieldNumber = 1;
    private uint unFetchInfo_;
    /// <summary>
    /// 领取回归奖励情况,二进制位表示
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnFetchInfo {
      get { return unFetchInfo_; }
      set {
        unFetchInfo_ = value;
      }
    }

    /// <summary>Field number for the "unInfoCount" field.</summary>
    public const int UnInfoCountFieldNumber = 2;
    private uint unInfoCount_;
    /// <summary>
    /// 礼包数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnInfoCount {
      get { return unInfoCount_; }
      set {
        unInfoCount_ = value;
      }
    }

    /// <summary>Field number for the "cFetchTimeInfo" field.</summary>
    public const int CFetchTimeInfoFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Sw.FetchTimeInfo> _repeated_cFetchTimeInfo_codec
        = pb::FieldCodec.ForMessage(26, global::Sw.FetchTimeInfo.Parser);
    private readonly pbc::RepeatedField<global::Sw.FetchTimeInfo> cFetchTimeInfo_ = new pbc::RepeatedField<global::Sw.FetchTimeInfo>();
    /// <summary>
    /// 领取时间对应天数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Sw.FetchTimeInfo> CFetchTimeInfo {
      get { return cFetchTimeInfo_; }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private uint unErrorCode_;
    /// <summary>
    /// 返回错误码 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgWelfareReturnQueryInfoS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgWelfareReturnQueryInfoS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnFetchInfo != other.UnFetchInfo) return false;
      if (UnInfoCount != other.UnInfoCount) return false;
      if(!cFetchTimeInfo_.Equals(other.cFetchTimeInfo_)) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnFetchInfo != 0) hash ^= UnFetchInfo.GetHashCode();
      if (UnInfoCount != 0) hash ^= UnInfoCount.GetHashCode();
      hash ^= cFetchTimeInfo_.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnFetchInfo != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UnFetchInfo);
      }
      if (UnInfoCount != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(UnInfoCount);
      }
      cFetchTimeInfo_.WriteTo(output, _repeated_cFetchTimeInfo_codec);
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteUInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnFetchInfo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnFetchInfo);
      }
      if (UnInfoCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnInfoCount);
      }
      size += cFetchTimeInfo_.CalculateSize(_repeated_cFetchTimeInfo_codec);
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgWelfareReturnQueryInfoS other) {
      if (other == null) {
        return;
      }
      if (other.UnFetchInfo != 0) {
        UnFetchInfo = other.UnFetchInfo;
      }
      if (other.UnInfoCount != 0) {
        UnInfoCount = other.UnInfoCount;
      }
      cFetchTimeInfo_.Add(other.cFetchTimeInfo_);
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnFetchInfo = input.ReadUInt32();
            break;
          }
          case 16: {
            UnInfoCount = input.ReadUInt32();
            break;
          }
          case 26: {
            cFetchTimeInfo_.AddEntriesFrom(input, _repeated_cFetchTimeInfo_codec);
            break;
          }
          case 792: {
            UnErrorCode = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端：领取回归礼包奖励请求
  /// _MSG_WELFARE_RETURN_FETCH_REWARD_C
  /// </summary>
  public sealed partial class PMsgWelfareReturnFetchRewardC : pb::IMessage<PMsgWelfareReturnFetchRewardC> {
    private static readonly pb::MessageParser<PMsgWelfareReturnFetchRewardC> _parser = new pb::MessageParser<PMsgWelfareReturnFetchRewardC>(() => new PMsgWelfareReturnFetchRewardC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgWelfareReturnFetchRewardC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgWelfareReturnReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnFetchRewardC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnFetchRewardC(PMsgWelfareReturnFetchRewardC other) : this() {
      unDay_ = other.unDay_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnFetchRewardC Clone() {
      return new PMsgWelfareReturnFetchRewardC(this);
    }

    /// <summary>Field number for the "unDay" field.</summary>
    public const int UnDayFieldNumber = 1;
    private uint unDay_;
    /// <summary>
    /// 领取第几天的回归奖励, EventCheck表Type_b=3;AttendanceDay_b字段的值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnDay {
      get { return unDay_; }
      set {
        unDay_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgWelfareReturnFetchRewardC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgWelfareReturnFetchRewardC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnDay != other.UnDay) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnDay != 0) hash ^= UnDay.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnDay != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UnDay);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnDay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnDay);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgWelfareReturnFetchRewardC other) {
      if (other == null) {
        return;
      }
      if (other.UnDay != 0) {
        UnDay = other.UnDay;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnDay = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务端：领取回归礼包奖励请求回复
  /// _MSG_WELFARE_RETURN_FETCH_REWARD_S
  /// </summary>
  public sealed partial class PMsgWelfareReturnFetchRewardS : pb::IMessage<PMsgWelfareReturnFetchRewardS> {
    private static readonly pb::MessageParser<PMsgWelfareReturnFetchRewardS> _parser = new pb::MessageParser<PMsgWelfareReturnFetchRewardS>(() => new PMsgWelfareReturnFetchRewardS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgWelfareReturnFetchRewardS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgWelfareReturnReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnFetchRewardS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnFetchRewardS(PMsgWelfareReturnFetchRewardS other) : this() {
      unFetchInfo_ = other.unFetchInfo_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgWelfareReturnFetchRewardS Clone() {
      return new PMsgWelfareReturnFetchRewardS(this);
    }

    /// <summary>Field number for the "unFetchInfo" field.</summary>
    public const int UnFetchInfoFieldNumber = 1;
    private uint unFetchInfo_;
    /// <summary>
    /// 领取回归奖励情况,二进制位表示
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnFetchInfo {
      get { return unFetchInfo_; }
      set {
        unFetchInfo_ = value;
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private uint unErrorCode_;
    /// <summary>
    /// 返回错误码 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgWelfareReturnFetchRewardS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgWelfareReturnFetchRewardS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnFetchInfo != other.UnFetchInfo) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnFetchInfo != 0) hash ^= UnFetchInfo.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnFetchInfo != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UnFetchInfo);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteUInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnFetchInfo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnFetchInfo);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgWelfareReturnFetchRewardS other) {
      if (other == null) {
        return;
      }
      if (other.UnFetchInfo != 0) {
        UnFetchInfo = other.UnFetchInfo;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnFetchInfo = input.ReadUInt32();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
