// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/PMsgBulletin.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sw {

  /// <summary>Holder for reflection information generated from protos/PMsgBulletin.proto</summary>
  public static partial class PMsgBulletinReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/PMsgBulletin.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PMsgBulletinReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chlwcm90b3MvUE1zZ0J1bGxldGluLnByb3RvEgJzdyJ4ChdQTXNnQnVsbGV0",
            "aW5TeW5OZXdJbmZvUxIOCgZ1blR5cGUYASABKA0SDwoHc3pUaXRsZRgCIAEo",
            "CRISCgpzekJ1bGxldGluGAMgASgJEhQKDHVsbEJlZ2luVGltZRgEIAEoBBIS",
            "Cgp1bGxFbmRUaW1lGAUgASgEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgBulletinSynNewInfoS), global::Sw.PMsgBulletinSynNewInfoS.Parser, new[]{ "UnType", "SzTitle", "SzBulletin", "UllBeginTime", "UllEndTime" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 服务器：同步新公告
  /// _MSG_NEW_SYN_BULLETIN_S
  /// </summary>
  public sealed partial class PMsgBulletinSynNewInfoS : pb::IMessage<PMsgBulletinSynNewInfoS> {
    private static readonly pb::MessageParser<PMsgBulletinSynNewInfoS> _parser = new pb::MessageParser<PMsgBulletinSynNewInfoS>(() => new PMsgBulletinSynNewInfoS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgBulletinSynNewInfoS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgBulletinReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgBulletinSynNewInfoS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgBulletinSynNewInfoS(PMsgBulletinSynNewInfoS other) : this() {
      unType_ = other.unType_;
      szTitle_ = other.szTitle_;
      szBulletin_ = other.szBulletin_;
      ullBeginTime_ = other.ullBeginTime_;
      ullEndTime_ = other.ullEndTime_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgBulletinSynNewInfoS Clone() {
      return new PMsgBulletinSynNewInfoS(this);
    }

    /// <summary>Field number for the "unType" field.</summary>
    public const int UnTypeFieldNumber = 1;
    private uint unType_;
    /// <summary>
    /// 公告类型	enum eBulletinType
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnType {
      get { return unType_; }
      set {
        unType_ = value;
      }
    }

    /// <summary>Field number for the "szTitle" field.</summary>
    public const int SzTitleFieldNumber = 2;
    private string szTitle_ = "";
    /// <summary>
    /// 公告标题
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzTitle {
      get { return szTitle_; }
      set {
        szTitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "szBulletin" field.</summary>
    public const int SzBulletinFieldNumber = 3;
    private string szBulletin_ = "";
    /// <summary>
    /// 公告内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzBulletin {
      get { return szBulletin_; }
      set {
        szBulletin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ullBeginTime" field.</summary>
    public const int UllBeginTimeFieldNumber = 4;
    private ulong ullBeginTime_;
    /// <summary>
    /// 公告开始时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UllBeginTime {
      get { return ullBeginTime_; }
      set {
        ullBeginTime_ = value;
      }
    }

    /// <summary>Field number for the "ullEndTime" field.</summary>
    public const int UllEndTimeFieldNumber = 5;
    private ulong ullEndTime_;
    /// <summary>
    /// 公告结束时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UllEndTime {
      get { return ullEndTime_; }
      set {
        ullEndTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgBulletinSynNewInfoS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgBulletinSynNewInfoS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnType != other.UnType) return false;
      if (SzTitle != other.SzTitle) return false;
      if (SzBulletin != other.SzBulletin) return false;
      if (UllBeginTime != other.UllBeginTime) return false;
      if (UllEndTime != other.UllEndTime) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnType != 0) hash ^= UnType.GetHashCode();
      if (SzTitle.Length != 0) hash ^= SzTitle.GetHashCode();
      if (SzBulletin.Length != 0) hash ^= SzBulletin.GetHashCode();
      if (UllBeginTime != 0UL) hash ^= UllBeginTime.GetHashCode();
      if (UllEndTime != 0UL) hash ^= UllEndTime.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UnType);
      }
      if (SzTitle.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SzTitle);
      }
      if (SzBulletin.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SzBulletin);
      }
      if (UllBeginTime != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(UllBeginTime);
      }
      if (UllEndTime != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(UllEndTime);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnType);
      }
      if (SzTitle.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzTitle);
      }
      if (SzBulletin.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzBulletin);
      }
      if (UllBeginTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UllBeginTime);
      }
      if (UllEndTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UllEndTime);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgBulletinSynNewInfoS other) {
      if (other == null) {
        return;
      }
      if (other.UnType != 0) {
        UnType = other.UnType;
      }
      if (other.SzTitle.Length != 0) {
        SzTitle = other.SzTitle;
      }
      if (other.SzBulletin.Length != 0) {
        SzBulletin = other.SzBulletin;
      }
      if (other.UllBeginTime != 0UL) {
        UllBeginTime = other.UllBeginTime;
      }
      if (other.UllEndTime != 0UL) {
        UllEndTime = other.UllEndTime;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnType = input.ReadUInt32();
            break;
          }
          case 18: {
            SzTitle = input.ReadString();
            break;
          }
          case 26: {
            SzBulletin = input.ReadString();
            break;
          }
          case 32: {
            UllBeginTime = input.ReadUInt64();
            break;
          }
          case 40: {
            UllEndTime = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
