// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/PMsgNpc.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sw {

  /// <summary>Holder for reflection information generated from protos/PMsgNpc.proto</summary>
  public static partial class PMsgNpcReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/PMsgNpc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PMsgNpcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRwcm90b3MvUE1zZ05wYy5wcm90bxICc3ciUwoMUE1zZ05wY0luZm9TEhAK",
            "CHVsbE5wY0lkGAEgASgDEhEKCXVuTnBjVHlwZRgCIAEoBRIOCgZ1blBvc1gY",
            "AyABKAUSDgoGdW5Qb3NZGAQgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgNpcInfoS), global::Sw.PMsgNpcInfoS.Parser, new[]{ "UllNpcId", "UnNpcType", "UnPosX", "UnPosY" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 服务器：进入地图（自己）
  /// _MSG_NPC_INFO_S
  /// </summary>
  public sealed partial class PMsgNpcInfoS : pb::IMessage<PMsgNpcInfoS> {
    private static readonly pb::MessageParser<PMsgNpcInfoS> _parser = new pb::MessageParser<PMsgNpcInfoS>(() => new PMsgNpcInfoS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgNpcInfoS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgNpcReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgNpcInfoS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgNpcInfoS(PMsgNpcInfoS other) : this() {
      ullNpcId_ = other.ullNpcId_;
      unNpcType_ = other.unNpcType_;
      unPosX_ = other.unPosX_;
      unPosY_ = other.unPosY_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgNpcInfoS Clone() {
      return new PMsgNpcInfoS(this);
    }

    /// <summary>Field number for the "ullNpcId" field.</summary>
    public const int UllNpcIdFieldNumber = 1;
    private long ullNpcId_;
    /// <summary>
    /// Npc_id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UllNpcId {
      get { return ullNpcId_; }
      set {
        ullNpcId_ = value;
      }
    }

    /// <summary>Field number for the "unNpcType" field.</summary>
    public const int UnNpcTypeFieldNumber = 2;
    private int unNpcType_;
    /// <summary>
    /// Npc类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnNpcType {
      get { return unNpcType_; }
      set {
        unNpcType_ = value;
      }
    }

    /// <summary>Field number for the "unPosX" field.</summary>
    public const int UnPosXFieldNumber = 3;
    private int unPosX_;
    /// <summary>
    /// 坐标：X
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnPosX {
      get { return unPosX_; }
      set {
        unPosX_ = value;
      }
    }

    /// <summary>Field number for the "unPosY" field.</summary>
    public const int UnPosYFieldNumber = 4;
    private int unPosY_;
    /// <summary>
    /// 坐标：Y
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnPosY {
      get { return unPosY_; }
      set {
        unPosY_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgNpcInfoS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgNpcInfoS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UllNpcId != other.UllNpcId) return false;
      if (UnNpcType != other.UnNpcType) return false;
      if (UnPosX != other.UnPosX) return false;
      if (UnPosY != other.UnPosY) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UllNpcId != 0L) hash ^= UllNpcId.GetHashCode();
      if (UnNpcType != 0) hash ^= UnNpcType.GetHashCode();
      if (UnPosX != 0) hash ^= UnPosX.GetHashCode();
      if (UnPosY != 0) hash ^= UnPosY.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UllNpcId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(UllNpcId);
      }
      if (UnNpcType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnNpcType);
      }
      if (UnPosX != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(UnPosX);
      }
      if (UnPosY != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(UnPosY);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UllNpcId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UllNpcId);
      }
      if (UnNpcType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnNpcType);
      }
      if (UnPosX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnPosX);
      }
      if (UnPosY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnPosY);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgNpcInfoS other) {
      if (other == null) {
        return;
      }
      if (other.UllNpcId != 0L) {
        UllNpcId = other.UllNpcId;
      }
      if (other.UnNpcType != 0) {
        UnNpcType = other.UnNpcType;
      }
      if (other.UnPosX != 0) {
        UnPosX = other.UnPosX;
      }
      if (other.UnPosY != 0) {
        UnPosY = other.UnPosY;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UllNpcId = input.ReadInt64();
            break;
          }
          case 16: {
            UnNpcType = input.ReadInt32();
            break;
          }
          case 24: {
            UnPosX = input.ReadInt32();
            break;
          }
          case 32: {
            UnPosY = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
