// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/PMsgHero.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sw {

  /// <summary>Holder for reflection information generated from protos/PMsgHero.proto</summary>
  public static partial class PMsgHeroReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/PMsgHero.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PMsgHeroReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVwcm90b3MvUE1zZ0hlcm8ucHJvdG8SAnN3IiQKDlBNc2dIZXJvUXVlcnlD",
            "EhIKCnVuUmVzZXJ2ZWQYASABKAUiOAoNSGVyb1NraWxsSW5mbxIRCgl1blNr",
            "aWxsSWQYASABKAUSFAoMdW5Ta2lsbExldmVsGAIgASgFIp0BCghIZXJvSW5m",
            "bxIQCgh1bkhlcm9JZBgBIAEoBRIOCgZ1blR5cGUYAiABKAUSDwoHdW5MZXZl",
            "bBgDIAEoBRIOCgZ1bGxFeHAYBCABKAMSFQoNdW5CYXNlU2tpbGxJZBgFIAEo",
            "BRIlCgpjU2tpbGxJbmZvGAYgAygLMhEuc3cuSGVyb1NraWxsSW5mbxIQCgh1",
            "bkF0dGFjaxgHIAEoBSI+Cg5QTXNnSGVyb1F1ZXJ5UxIPCgd1bkNvdW50GAEg",
            "ASgFEhsKBWNJbmZvGAIgAygLMgwuc3cuSGVyb0luZm8iJQoPUE1zZ0hlcm9G",
            "dXNpb25DEhIKCnVuSGVyb1R5cGUYASABKAUiOgoPUE1zZ0hlcm9GdXNpb25T",
            "EhIKCnVuSGVyb1R5cGUYASABKAUSEwoLdW5FcnJvckNvZGUYYyABKAUiTAoT",
            "UE1zZ0hlcm9Vc2VFeHBJdGVtQxIQCgh1bkhlcm9JZBgBIAEoBRIQCgh1bkl0",
            "ZW1JZBgCIAEoBRIRCgl1bkl0ZW1OdW0YAyABKAUiYQoTUE1zZ0hlcm9Vc2VF",
            "eHBJdGVtUxIQCgh1bkhlcm9JZBgBIAEoBRIQCgh1bkl0ZW1JZBgCIAEoBRIR",
            "Cgl1bkl0ZW1OdW0YAyABKAUSEwoLdW5FcnJvckNvZGUYYyABKAUiIwoPUE1z",
            "Z0hlcm9Fdm9sdmVDEhAKCHVuSGVyb0lkGAEgASgFIjgKD1BNc2dIZXJvRXZv",
            "bHZlUxIQCgh1bkhlcm9JZBgBIAEoBRITCgt1bkVycm9yQ29kZRhjIAEoBSI9",
            "ChVQTXNnSGVyb1NraWxsVXBncmFkZUMSEAoIdW5IZXJvSWQYASABKAUSEgoK",
            "dW5Ta2lsbElkeBgCIAEoBSJSChVQTXNnSGVyb1NraWxsVXBncmFkZVMSEAoI",
            "dW5IZXJvSWQYASABKAUSEgoKdW5Ta2lsbElkeBgCIAEoBRITCgt1bkVycm9y",
            "Q29kZRhjIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgHeroQueryC), global::Sw.PMsgHeroQueryC.Parser, new[]{ "UnReserved" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.HeroSkillInfo), global::Sw.HeroSkillInfo.Parser, new[]{ "UnSkillId", "UnSkillLevel" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.HeroInfo), global::Sw.HeroInfo.Parser, new[]{ "UnHeroId", "UnType", "UnLevel", "UllExp", "UnBaseSkillId", "CSkillInfo", "UnAttack" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgHeroQueryS), global::Sw.PMsgHeroQueryS.Parser, new[]{ "UnCount", "CInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgHeroFusionC), global::Sw.PMsgHeroFusionC.Parser, new[]{ "UnHeroType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgHeroFusionS), global::Sw.PMsgHeroFusionS.Parser, new[]{ "UnHeroType", "UnErrorCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgHeroUseExpItemC), global::Sw.PMsgHeroUseExpItemC.Parser, new[]{ "UnHeroId", "UnItemId", "UnItemNum" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgHeroUseExpItemS), global::Sw.PMsgHeroUseExpItemS.Parser, new[]{ "UnHeroId", "UnItemId", "UnItemNum", "UnErrorCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgHeroEvolveC), global::Sw.PMsgHeroEvolveC.Parser, new[]{ "UnHeroId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgHeroEvolveS), global::Sw.PMsgHeroEvolveS.Parser, new[]{ "UnHeroId", "UnErrorCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgHeroSkillUpgradeC), global::Sw.PMsgHeroSkillUpgradeC.Parser, new[]{ "UnHeroId", "UnSkillIdx" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgHeroSkillUpgradeS), global::Sw.PMsgHeroSkillUpgradeS.Parser, new[]{ "UnHeroId", "UnSkillIdx", "UnErrorCode" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 客户端：查询伙伴信息
  /// _MSG_HERO_QUERY_C
  /// </summary>
  public sealed partial class PMsgHeroQueryC : pb::IMessage<PMsgHeroQueryC> {
    private static readonly pb::MessageParser<PMsgHeroQueryC> _parser = new pb::MessageParser<PMsgHeroQueryC>(() => new PMsgHeroQueryC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgHeroQueryC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroQueryC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroQueryC(PMsgHeroQueryC other) : this() {
      unReserved_ = other.unReserved_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroQueryC Clone() {
      return new PMsgHeroQueryC(this);
    }

    /// <summary>Field number for the "unReserved" field.</summary>
    public const int UnReservedFieldNumber = 1;
    private int unReserved_;
    /// <summary>
    /// 保留字段
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnReserved {
      get { return unReserved_; }
      set {
        unReserved_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgHeroQueryC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgHeroQueryC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnReserved != other.UnReserved) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnReserved != 0) hash ^= UnReserved.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnReserved != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnReserved);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnReserved != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnReserved);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgHeroQueryC other) {
      if (other == null) {
        return;
      }
      if (other.UnReserved != 0) {
        UnReserved = other.UnReserved;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnReserved = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 伙伴主动技能信息
  /// </summary>
  public sealed partial class HeroSkillInfo : pb::IMessage<HeroSkillInfo> {
    private static readonly pb::MessageParser<HeroSkillInfo> _parser = new pb::MessageParser<HeroSkillInfo>(() => new HeroSkillInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HeroSkillInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeroSkillInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeroSkillInfo(HeroSkillInfo other) : this() {
      unSkillId_ = other.unSkillId_;
      unSkillLevel_ = other.unSkillLevel_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeroSkillInfo Clone() {
      return new HeroSkillInfo(this);
    }

    /// <summary>Field number for the "unSkillId" field.</summary>
    public const int UnSkillIdFieldNumber = 1;
    private int unSkillId_;
    /// <summary>
    /// 技能id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnSkillId {
      get { return unSkillId_; }
      set {
        unSkillId_ = value;
      }
    }

    /// <summary>Field number for the "unSkillLevel" field.</summary>
    public const int UnSkillLevelFieldNumber = 2;
    private int unSkillLevel_;
    /// <summary>
    /// 等级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnSkillLevel {
      get { return unSkillLevel_; }
      set {
        unSkillLevel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HeroSkillInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HeroSkillInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnSkillId != other.UnSkillId) return false;
      if (UnSkillLevel != other.UnSkillLevel) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnSkillId != 0) hash ^= UnSkillId.GetHashCode();
      if (UnSkillLevel != 0) hash ^= UnSkillLevel.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnSkillId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnSkillId);
      }
      if (UnSkillLevel != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnSkillLevel);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnSkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnSkillId);
      }
      if (UnSkillLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnSkillLevel);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HeroSkillInfo other) {
      if (other == null) {
        return;
      }
      if (other.UnSkillId != 0) {
        UnSkillId = other.UnSkillId;
      }
      if (other.UnSkillLevel != 0) {
        UnSkillLevel = other.UnSkillLevel;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnSkillId = input.ReadInt32();
            break;
          }
          case 16: {
            UnSkillLevel = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 伙伴基本信息
  /// </summary>
  public sealed partial class HeroInfo : pb::IMessage<HeroInfo> {
    private static readonly pb::MessageParser<HeroInfo> _parser = new pb::MessageParser<HeroInfo>(() => new HeroInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HeroInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeroInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeroInfo(HeroInfo other) : this() {
      unHeroId_ = other.unHeroId_;
      unType_ = other.unType_;
      unLevel_ = other.unLevel_;
      ullExp_ = other.ullExp_;
      unBaseSkillId_ = other.unBaseSkillId_;
      cSkillInfo_ = other.cSkillInfo_.Clone();
      unAttack_ = other.unAttack_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeroInfo Clone() {
      return new HeroInfo(this);
    }

    /// <summary>Field number for the "unHeroId" field.</summary>
    public const int UnHeroIdFieldNumber = 1;
    private int unHeroId_;
    /// <summary>
    /// 伙伴id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnHeroId {
      get { return unHeroId_; }
      set {
        unHeroId_ = value;
      }
    }

    /// <summary>Field number for the "unType" field.</summary>
    public const int UnTypeFieldNumber = 2;
    private int unType_;
    /// <summary>
    /// 类型（品质）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnType {
      get { return unType_; }
      set {
        unType_ = value;
      }
    }

    /// <summary>Field number for the "unLevel" field.</summary>
    public const int UnLevelFieldNumber = 3;
    private int unLevel_;
    /// <summary>
    /// 等级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnLevel {
      get { return unLevel_; }
      set {
        unLevel_ = value;
      }
    }

    /// <summary>Field number for the "ullExp" field.</summary>
    public const int UllExpFieldNumber = 4;
    private long ullExp_;
    /// <summary>
    /// 经验
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UllExp {
      get { return ullExp_; }
      set {
        ullExp_ = value;
      }
    }

    /// <summary>Field number for the "unBaseSkillId" field.</summary>
    public const int UnBaseSkillIdFieldNumber = 5;
    private int unBaseSkillId_;
    /// <summary>
    /// 普攻技能
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnBaseSkillId {
      get { return unBaseSkillId_; }
      set {
        unBaseSkillId_ = value;
      }
    }

    /// <summary>Field number for the "cSkillInfo" field.</summary>
    public const int CSkillInfoFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Sw.HeroSkillInfo> _repeated_cSkillInfo_codec
        = pb::FieldCodec.ForMessage(50, global::Sw.HeroSkillInfo.Parser);
    private readonly pbc::RepeatedField<global::Sw.HeroSkillInfo> cSkillInfo_ = new pbc::RepeatedField<global::Sw.HeroSkillInfo>();
    /// <summary>
    /// 主动技能信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Sw.HeroSkillInfo> CSkillInfo {
      get { return cSkillInfo_; }
    }

    /// <summary>Field number for the "unAttack" field.</summary>
    public const int UnAttackFieldNumber = 7;
    private int unAttack_;
    /// <summary>
    /// 战斗力
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnAttack {
      get { return unAttack_; }
      set {
        unAttack_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HeroInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HeroInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnHeroId != other.UnHeroId) return false;
      if (UnType != other.UnType) return false;
      if (UnLevel != other.UnLevel) return false;
      if (UllExp != other.UllExp) return false;
      if (UnBaseSkillId != other.UnBaseSkillId) return false;
      if(!cSkillInfo_.Equals(other.cSkillInfo_)) return false;
      if (UnAttack != other.UnAttack) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnHeroId != 0) hash ^= UnHeroId.GetHashCode();
      if (UnType != 0) hash ^= UnType.GetHashCode();
      if (UnLevel != 0) hash ^= UnLevel.GetHashCode();
      if (UllExp != 0L) hash ^= UllExp.GetHashCode();
      if (UnBaseSkillId != 0) hash ^= UnBaseSkillId.GetHashCode();
      hash ^= cSkillInfo_.GetHashCode();
      if (UnAttack != 0) hash ^= UnAttack.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnHeroId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnHeroId);
      }
      if (UnType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnType);
      }
      if (UnLevel != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(UnLevel);
      }
      if (UllExp != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(UllExp);
      }
      if (UnBaseSkillId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(UnBaseSkillId);
      }
      cSkillInfo_.WriteTo(output, _repeated_cSkillInfo_codec);
      if (UnAttack != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(UnAttack);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnHeroId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnHeroId);
      }
      if (UnType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnType);
      }
      if (UnLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnLevel);
      }
      if (UllExp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UllExp);
      }
      if (UnBaseSkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnBaseSkillId);
      }
      size += cSkillInfo_.CalculateSize(_repeated_cSkillInfo_codec);
      if (UnAttack != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnAttack);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HeroInfo other) {
      if (other == null) {
        return;
      }
      if (other.UnHeroId != 0) {
        UnHeroId = other.UnHeroId;
      }
      if (other.UnType != 0) {
        UnType = other.UnType;
      }
      if (other.UnLevel != 0) {
        UnLevel = other.UnLevel;
      }
      if (other.UllExp != 0L) {
        UllExp = other.UllExp;
      }
      if (other.UnBaseSkillId != 0) {
        UnBaseSkillId = other.UnBaseSkillId;
      }
      cSkillInfo_.Add(other.cSkillInfo_);
      if (other.UnAttack != 0) {
        UnAttack = other.UnAttack;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnHeroId = input.ReadInt32();
            break;
          }
          case 16: {
            UnType = input.ReadInt32();
            break;
          }
          case 24: {
            UnLevel = input.ReadInt32();
            break;
          }
          case 32: {
            UllExp = input.ReadInt64();
            break;
          }
          case 40: {
            UnBaseSkillId = input.ReadInt32();
            break;
          }
          case 50: {
            cSkillInfo_.AddEntriesFrom(input, _repeated_cSkillInfo_codec);
            break;
          }
          case 56: {
            UnAttack = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：查询伙伴信息回复
  /// _MSG_HERO_QUERY_S
  /// </summary>
  public sealed partial class PMsgHeroQueryS : pb::IMessage<PMsgHeroQueryS> {
    private static readonly pb::MessageParser<PMsgHeroQueryS> _parser = new pb::MessageParser<PMsgHeroQueryS>(() => new PMsgHeroQueryS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgHeroQueryS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroQueryS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroQueryS(PMsgHeroQueryS other) : this() {
      unCount_ = other.unCount_;
      cInfo_ = other.cInfo_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroQueryS Clone() {
      return new PMsgHeroQueryS(this);
    }

    /// <summary>Field number for the "unCount" field.</summary>
    public const int UnCountFieldNumber = 1;
    private int unCount_;
    /// <summary>
    /// 伙伴数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnCount {
      get { return unCount_; }
      set {
        unCount_ = value;
      }
    }

    /// <summary>Field number for the "cInfo" field.</summary>
    public const int CInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Sw.HeroInfo> _repeated_cInfo_codec
        = pb::FieldCodec.ForMessage(18, global::Sw.HeroInfo.Parser);
    private readonly pbc::RepeatedField<global::Sw.HeroInfo> cInfo_ = new pbc::RepeatedField<global::Sw.HeroInfo>();
    /// <summary>
    /// 伙伴信息列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Sw.HeroInfo> CInfo {
      get { return cInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgHeroQueryS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgHeroQueryS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnCount != other.UnCount) return false;
      if(!cInfo_.Equals(other.cInfo_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnCount != 0) hash ^= UnCount.GetHashCode();
      hash ^= cInfo_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnCount);
      }
      cInfo_.WriteTo(output, _repeated_cInfo_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnCount);
      }
      size += cInfo_.CalculateSize(_repeated_cInfo_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgHeroQueryS other) {
      if (other == null) {
        return;
      }
      if (other.UnCount != 0) {
        UnCount = other.UnCount;
      }
      cInfo_.Add(other.cInfo_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnCount = input.ReadInt32();
            break;
          }
          case 18: {
            cInfo_.AddEntriesFrom(input, _repeated_cInfo_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端：伙伴合成（召唤）
  /// _MSG_HERO_FUSION_C
  /// </summary>
  public sealed partial class PMsgHeroFusionC : pb::IMessage<PMsgHeroFusionC> {
    private static readonly pb::MessageParser<PMsgHeroFusionC> _parser = new pb::MessageParser<PMsgHeroFusionC>(() => new PMsgHeroFusionC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgHeroFusionC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroFusionC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroFusionC(PMsgHeroFusionC other) : this() {
      unHeroType_ = other.unHeroType_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroFusionC Clone() {
      return new PMsgHeroFusionC(this);
    }

    /// <summary>Field number for the "unHeroType" field.</summary>
    public const int UnHeroTypeFieldNumber = 1;
    private int unHeroType_;
    /// <summary>
    /// 伙伴类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnHeroType {
      get { return unHeroType_; }
      set {
        unHeroType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgHeroFusionC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgHeroFusionC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnHeroType != other.UnHeroType) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnHeroType != 0) hash ^= UnHeroType.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnHeroType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnHeroType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnHeroType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnHeroType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgHeroFusionC other) {
      if (other == null) {
        return;
      }
      if (other.UnHeroType != 0) {
        UnHeroType = other.UnHeroType;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnHeroType = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：伙伴合成（召唤）回复
  /// _MSG_HERO_FUSION_S
  /// </summary>
  public sealed partial class PMsgHeroFusionS : pb::IMessage<PMsgHeroFusionS> {
    private static readonly pb::MessageParser<PMsgHeroFusionS> _parser = new pb::MessageParser<PMsgHeroFusionS>(() => new PMsgHeroFusionS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgHeroFusionS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroFusionS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroFusionS(PMsgHeroFusionS other) : this() {
      unHeroType_ = other.unHeroType_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroFusionS Clone() {
      return new PMsgHeroFusionS(this);
    }

    /// <summary>Field number for the "unHeroType" field.</summary>
    public const int UnHeroTypeFieldNumber = 1;
    private int unHeroType_;
    /// <summary>
    /// 伙伴类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnHeroType {
      get { return unHeroType_; }
      set {
        unHeroType_ = value;
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private int unErrorCode_;
    /// <summary>
    /// 返回错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgHeroFusionS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgHeroFusionS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnHeroType != other.UnHeroType) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnHeroType != 0) hash ^= UnHeroType.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnHeroType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnHeroType);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnHeroType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnHeroType);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgHeroFusionS other) {
      if (other == null) {
        return;
      }
      if (other.UnHeroType != 0) {
        UnHeroType = other.UnHeroType;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnHeroType = input.ReadInt32();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端：伙伴使用经验道具
  /// _MSG_HERO_USE_EXP_ITEM_C
  /// </summary>
  public sealed partial class PMsgHeroUseExpItemC : pb::IMessage<PMsgHeroUseExpItemC> {
    private static readonly pb::MessageParser<PMsgHeroUseExpItemC> _parser = new pb::MessageParser<PMsgHeroUseExpItemC>(() => new PMsgHeroUseExpItemC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgHeroUseExpItemC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroUseExpItemC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroUseExpItemC(PMsgHeroUseExpItemC other) : this() {
      unHeroId_ = other.unHeroId_;
      unItemId_ = other.unItemId_;
      unItemNum_ = other.unItemNum_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroUseExpItemC Clone() {
      return new PMsgHeroUseExpItemC(this);
    }

    /// <summary>Field number for the "unHeroId" field.</summary>
    public const int UnHeroIdFieldNumber = 1;
    private int unHeroId_;
    /// <summary>
    /// 伙伴id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnHeroId {
      get { return unHeroId_; }
      set {
        unHeroId_ = value;
      }
    }

    /// <summary>Field number for the "unItemId" field.</summary>
    public const int UnItemIdFieldNumber = 2;
    private int unItemId_;
    /// <summary>
    /// 经验道具id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnItemId {
      get { return unItemId_; }
      set {
        unItemId_ = value;
      }
    }

    /// <summary>Field number for the "unItemNum" field.</summary>
    public const int UnItemNumFieldNumber = 3;
    private int unItemNum_;
    /// <summary>
    /// 经验道具数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnItemNum {
      get { return unItemNum_; }
      set {
        unItemNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgHeroUseExpItemC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgHeroUseExpItemC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnHeroId != other.UnHeroId) return false;
      if (UnItemId != other.UnItemId) return false;
      if (UnItemNum != other.UnItemNum) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnHeroId != 0) hash ^= UnHeroId.GetHashCode();
      if (UnItemId != 0) hash ^= UnItemId.GetHashCode();
      if (UnItemNum != 0) hash ^= UnItemNum.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnHeroId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnHeroId);
      }
      if (UnItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnItemId);
      }
      if (UnItemNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(UnItemNum);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnHeroId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnHeroId);
      }
      if (UnItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnItemId);
      }
      if (UnItemNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnItemNum);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgHeroUseExpItemC other) {
      if (other == null) {
        return;
      }
      if (other.UnHeroId != 0) {
        UnHeroId = other.UnHeroId;
      }
      if (other.UnItemId != 0) {
        UnItemId = other.UnItemId;
      }
      if (other.UnItemNum != 0) {
        UnItemNum = other.UnItemNum;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnHeroId = input.ReadInt32();
            break;
          }
          case 16: {
            UnItemId = input.ReadInt32();
            break;
          }
          case 24: {
            UnItemNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：伙伴使用经验道具回复
  /// _MSG_HERO_USE_EXP_ITEM_S
  /// </summary>
  public sealed partial class PMsgHeroUseExpItemS : pb::IMessage<PMsgHeroUseExpItemS> {
    private static readonly pb::MessageParser<PMsgHeroUseExpItemS> _parser = new pb::MessageParser<PMsgHeroUseExpItemS>(() => new PMsgHeroUseExpItemS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgHeroUseExpItemS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroUseExpItemS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroUseExpItemS(PMsgHeroUseExpItemS other) : this() {
      unHeroId_ = other.unHeroId_;
      unItemId_ = other.unItemId_;
      unItemNum_ = other.unItemNum_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroUseExpItemS Clone() {
      return new PMsgHeroUseExpItemS(this);
    }

    /// <summary>Field number for the "unHeroId" field.</summary>
    public const int UnHeroIdFieldNumber = 1;
    private int unHeroId_;
    /// <summary>
    /// 伙伴id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnHeroId {
      get { return unHeroId_; }
      set {
        unHeroId_ = value;
      }
    }

    /// <summary>Field number for the "unItemId" field.</summary>
    public const int UnItemIdFieldNumber = 2;
    private int unItemId_;
    /// <summary>
    /// 经验道具id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnItemId {
      get { return unItemId_; }
      set {
        unItemId_ = value;
      }
    }

    /// <summary>Field number for the "unItemNum" field.</summary>
    public const int UnItemNumFieldNumber = 3;
    private int unItemNum_;
    /// <summary>
    /// 经验道具数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnItemNum {
      get { return unItemNum_; }
      set {
        unItemNum_ = value;
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private int unErrorCode_;
    /// <summary>
    /// 返回错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgHeroUseExpItemS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgHeroUseExpItemS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnHeroId != other.UnHeroId) return false;
      if (UnItemId != other.UnItemId) return false;
      if (UnItemNum != other.UnItemNum) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnHeroId != 0) hash ^= UnHeroId.GetHashCode();
      if (UnItemId != 0) hash ^= UnItemId.GetHashCode();
      if (UnItemNum != 0) hash ^= UnItemNum.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnHeroId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnHeroId);
      }
      if (UnItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnItemId);
      }
      if (UnItemNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(UnItemNum);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnHeroId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnHeroId);
      }
      if (UnItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnItemId);
      }
      if (UnItemNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnItemNum);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgHeroUseExpItemS other) {
      if (other == null) {
        return;
      }
      if (other.UnHeroId != 0) {
        UnHeroId = other.UnHeroId;
      }
      if (other.UnItemId != 0) {
        UnItemId = other.UnItemId;
      }
      if (other.UnItemNum != 0) {
        UnItemNum = other.UnItemNum;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnHeroId = input.ReadInt32();
            break;
          }
          case 16: {
            UnItemId = input.ReadInt32();
            break;
          }
          case 24: {
            UnItemNum = input.ReadInt32();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端：伙伴晋级
  /// _MSG_HERO_EVOLVE_C
  /// </summary>
  public sealed partial class PMsgHeroEvolveC : pb::IMessage<PMsgHeroEvolveC> {
    private static readonly pb::MessageParser<PMsgHeroEvolveC> _parser = new pb::MessageParser<PMsgHeroEvolveC>(() => new PMsgHeroEvolveC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgHeroEvolveC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroEvolveC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroEvolveC(PMsgHeroEvolveC other) : this() {
      unHeroId_ = other.unHeroId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroEvolveC Clone() {
      return new PMsgHeroEvolveC(this);
    }

    /// <summary>Field number for the "unHeroId" field.</summary>
    public const int UnHeroIdFieldNumber = 1;
    private int unHeroId_;
    /// <summary>
    /// 伙伴id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnHeroId {
      get { return unHeroId_; }
      set {
        unHeroId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgHeroEvolveC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgHeroEvolveC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnHeroId != other.UnHeroId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnHeroId != 0) hash ^= UnHeroId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnHeroId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnHeroId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnHeroId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnHeroId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgHeroEvolveC other) {
      if (other == null) {
        return;
      }
      if (other.UnHeroId != 0) {
        UnHeroId = other.UnHeroId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnHeroId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：伙伴晋级回复
  /// _MSG_HERO_EVOLVE_S
  /// </summary>
  public sealed partial class PMsgHeroEvolveS : pb::IMessage<PMsgHeroEvolveS> {
    private static readonly pb::MessageParser<PMsgHeroEvolveS> _parser = new pb::MessageParser<PMsgHeroEvolveS>(() => new PMsgHeroEvolveS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgHeroEvolveS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroEvolveS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroEvolveS(PMsgHeroEvolveS other) : this() {
      unHeroId_ = other.unHeroId_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroEvolveS Clone() {
      return new PMsgHeroEvolveS(this);
    }

    /// <summary>Field number for the "unHeroId" field.</summary>
    public const int UnHeroIdFieldNumber = 1;
    private int unHeroId_;
    /// <summary>
    /// 伙伴id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnHeroId {
      get { return unHeroId_; }
      set {
        unHeroId_ = value;
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private int unErrorCode_;
    /// <summary>
    /// 返回错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgHeroEvolveS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgHeroEvolveS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnHeroId != other.UnHeroId) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnHeroId != 0) hash ^= UnHeroId.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnHeroId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnHeroId);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnHeroId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnHeroId);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgHeroEvolveS other) {
      if (other == null) {
        return;
      }
      if (other.UnHeroId != 0) {
        UnHeroId = other.UnHeroId;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnHeroId = input.ReadInt32();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端：伙伴主动技能升级
  /// _MSG_HERO_SKILL_UPGRADE_C
  /// </summary>
  public sealed partial class PMsgHeroSkillUpgradeC : pb::IMessage<PMsgHeroSkillUpgradeC> {
    private static readonly pb::MessageParser<PMsgHeroSkillUpgradeC> _parser = new pb::MessageParser<PMsgHeroSkillUpgradeC>(() => new PMsgHeroSkillUpgradeC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgHeroSkillUpgradeC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroSkillUpgradeC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroSkillUpgradeC(PMsgHeroSkillUpgradeC other) : this() {
      unHeroId_ = other.unHeroId_;
      unSkillIdx_ = other.unSkillIdx_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroSkillUpgradeC Clone() {
      return new PMsgHeroSkillUpgradeC(this);
    }

    /// <summary>Field number for the "unHeroId" field.</summary>
    public const int UnHeroIdFieldNumber = 1;
    private int unHeroId_;
    /// <summary>
    /// 伙伴id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnHeroId {
      get { return unHeroId_; }
      set {
        unHeroId_ = value;
      }
    }

    /// <summary>Field number for the "unSkillIdx" field.</summary>
    public const int UnSkillIdxFieldNumber = 2;
    private int unSkillIdx_;
    /// <summary>
    /// 主动技能id：1~4
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnSkillIdx {
      get { return unSkillIdx_; }
      set {
        unSkillIdx_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgHeroSkillUpgradeC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgHeroSkillUpgradeC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnHeroId != other.UnHeroId) return false;
      if (UnSkillIdx != other.UnSkillIdx) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnHeroId != 0) hash ^= UnHeroId.GetHashCode();
      if (UnSkillIdx != 0) hash ^= UnSkillIdx.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnHeroId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnHeroId);
      }
      if (UnSkillIdx != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnSkillIdx);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnHeroId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnHeroId);
      }
      if (UnSkillIdx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnSkillIdx);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgHeroSkillUpgradeC other) {
      if (other == null) {
        return;
      }
      if (other.UnHeroId != 0) {
        UnHeroId = other.UnHeroId;
      }
      if (other.UnSkillIdx != 0) {
        UnSkillIdx = other.UnSkillIdx;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnHeroId = input.ReadInt32();
            break;
          }
          case 16: {
            UnSkillIdx = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：伙伴主动技能升级回复
  /// _MSG_HERO_SKILL_UPGRADE_S
  /// </summary>
  public sealed partial class PMsgHeroSkillUpgradeS : pb::IMessage<PMsgHeroSkillUpgradeS> {
    private static readonly pb::MessageParser<PMsgHeroSkillUpgradeS> _parser = new pb::MessageParser<PMsgHeroSkillUpgradeS>(() => new PMsgHeroSkillUpgradeS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgHeroSkillUpgradeS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgHeroReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroSkillUpgradeS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroSkillUpgradeS(PMsgHeroSkillUpgradeS other) : this() {
      unHeroId_ = other.unHeroId_;
      unSkillIdx_ = other.unSkillIdx_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgHeroSkillUpgradeS Clone() {
      return new PMsgHeroSkillUpgradeS(this);
    }

    /// <summary>Field number for the "unHeroId" field.</summary>
    public const int UnHeroIdFieldNumber = 1;
    private int unHeroId_;
    /// <summary>
    /// 伙伴id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnHeroId {
      get { return unHeroId_; }
      set {
        unHeroId_ = value;
      }
    }

    /// <summary>Field number for the "unSkillIdx" field.</summary>
    public const int UnSkillIdxFieldNumber = 2;
    private int unSkillIdx_;
    /// <summary>
    /// 主动技能id：1~4
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnSkillIdx {
      get { return unSkillIdx_; }
      set {
        unSkillIdx_ = value;
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private int unErrorCode_;
    /// <summary>
    /// 返回错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgHeroSkillUpgradeS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgHeroSkillUpgradeS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnHeroId != other.UnHeroId) return false;
      if (UnSkillIdx != other.UnSkillIdx) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnHeroId != 0) hash ^= UnHeroId.GetHashCode();
      if (UnSkillIdx != 0) hash ^= UnSkillIdx.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnHeroId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnHeroId);
      }
      if (UnSkillIdx != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnSkillIdx);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnHeroId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnHeroId);
      }
      if (UnSkillIdx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnSkillIdx);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgHeroSkillUpgradeS other) {
      if (other == null) {
        return;
      }
      if (other.UnHeroId != 0) {
        UnHeroId = other.UnHeroId;
      }
      if (other.UnSkillIdx != 0) {
        UnSkillIdx = other.UnSkillIdx;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnHeroId = input.ReadInt32();
            break;
          }
          case 16: {
            UnSkillIdx = input.ReadInt32();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
