// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/PMsgRechargeConsumer.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sw {

  /// <summary>Holder for reflection information generated from protos/PMsgRechargeConsumer.proto</summary>
  public static partial class PMsgRechargeConsumerReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/PMsgRechargeConsumer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PMsgRechargeConsumerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFwcm90b3MvUE1zZ1JlY2hhcmdlQ29uc3VtZXIucHJvdG8SAnN3IjMKHlBN",
            "c2dSZWNoYXJnZUNvbnN1bWVyUXVlcnlJbmZvQxIRCgluUmVzZXJ2ZWQYASAB",
            "KAUieQoeUE1zZ1JlY2hhcmdlQ29uc3VtZXJRdWVyeUluZm9TEhUKDXVsbE1v",
            "bmV5VG90YWwYASABKAQSEwoLdW5GZXRjaEluZm8YAiABKA0SFgoOdW5DYW5G",
            "ZXRjaEluZm8YAyABKA0SEwoLdW5FcnJvckNvZGUYYyABKA0iOgogUE1zZ1Jl",
            "Y2hhcmdlQ29uc3VtZXJTeW5DYW5GZXRjaFMSFgoOdW5DYW5GZXRjaEluZm8Y",
            "ASABKA0iOAogUE1zZ1JlY2hhcmdlQ29uc3VtZXJGZXRjaFJld2FyZEMSFAoM",
            "dW5GZXRjaExldmVsGAEgASgNImMKIFBNc2dSZWNoYXJnZUNvbnN1bWVyRmV0",
            "Y2hSZXdhcmRTEhUKDXVsbE1vbmV5VG90YWwYASABKAQSEwoLdW5GZXRjaElu",
            "Zm8YAiABKA0SEwoLdW5FcnJvckNvZGUYYyABKA1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeConsumerQueryInfoC), global::Sw.PMsgRechargeConsumerQueryInfoC.Parser, new[]{ "NReserved" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeConsumerQueryInfoS), global::Sw.PMsgRechargeConsumerQueryInfoS.Parser, new[]{ "UllMoneyTotal", "UnFetchInfo", "UnCanFetchInfo", "UnErrorCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeConsumerSynCanFetchS), global::Sw.PMsgRechargeConsumerSynCanFetchS.Parser, new[]{ "UnCanFetchInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeConsumerFetchRewardC), global::Sw.PMsgRechargeConsumerFetchRewardC.Parser, new[]{ "UnFetchLevel" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeConsumerFetchRewardS), global::Sw.PMsgRechargeConsumerFetchRewardS.Parser, new[]{ "UllMoneyTotal", "UnFetchInfo", "UnErrorCode" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 客户端：查询充值消费金额累积相关信息请求
  /// _MSG_RECHARGE_CONSUMER_QUERY_INFO_C
  /// </summary>
  public sealed partial class PMsgRechargeConsumerQueryInfoC : pb::IMessage<PMsgRechargeConsumerQueryInfoC> {
    private static readonly pb::MessageParser<PMsgRechargeConsumerQueryInfoC> _parser = new pb::MessageParser<PMsgRechargeConsumerQueryInfoC>(() => new PMsgRechargeConsumerQueryInfoC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeConsumerQueryInfoC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeConsumerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerQueryInfoC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerQueryInfoC(PMsgRechargeConsumerQueryInfoC other) : this() {
      nReserved_ = other.nReserved_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerQueryInfoC Clone() {
      return new PMsgRechargeConsumerQueryInfoC(this);
    }

    /// <summary>Field number for the "nReserved" field.</summary>
    public const int NReservedFieldNumber = 1;
    private int nReserved_;
    /// <summary>
    /// 保留字段
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NReserved {
      get { return nReserved_; }
      set {
        nReserved_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeConsumerQueryInfoC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeConsumerQueryInfoC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NReserved != other.NReserved) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NReserved != 0) hash ^= NReserved.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NReserved != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(NReserved);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NReserved != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NReserved);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeConsumerQueryInfoC other) {
      if (other == null) {
        return;
      }
      if (other.NReserved != 0) {
        NReserved = other.NReserved;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            NReserved = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务端：查询充值消费金额累积相关信息请求回复
  /// _MSG_RECHARGE_CONSUMER_QUERY_INFO_S
  /// </summary>
  public sealed partial class PMsgRechargeConsumerQueryInfoS : pb::IMessage<PMsgRechargeConsumerQueryInfoS> {
    private static readonly pb::MessageParser<PMsgRechargeConsumerQueryInfoS> _parser = new pb::MessageParser<PMsgRechargeConsumerQueryInfoS>(() => new PMsgRechargeConsumerQueryInfoS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeConsumerQueryInfoS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeConsumerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerQueryInfoS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerQueryInfoS(PMsgRechargeConsumerQueryInfoS other) : this() {
      ullMoneyTotal_ = other.ullMoneyTotal_;
      unFetchInfo_ = other.unFetchInfo_;
      unCanFetchInfo_ = other.unCanFetchInfo_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerQueryInfoS Clone() {
      return new PMsgRechargeConsumerQueryInfoS(this);
    }

    /// <summary>Field number for the "ullMoneyTotal" field.</summary>
    public const int UllMoneyTotalFieldNumber = 1;
    private ulong ullMoneyTotal_;
    /// <summary>
    /// 充值消费金额累积数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UllMoneyTotal {
      get { return ullMoneyTotal_; }
      set {
        ullMoneyTotal_ = value;
      }
    }

    /// <summary>Field number for the "unFetchInfo" field.</summary>
    public const int UnFetchInfoFieldNumber = 2;
    private uint unFetchInfo_;
    /// <summary>
    /// 领取累积充值奖励情况,二进制位表示
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnFetchInfo {
      get { return unFetchInfo_; }
      set {
        unFetchInfo_ = value;
      }
    }

    /// <summary>Field number for the "unCanFetchInfo" field.</summary>
    public const int UnCanFetchInfoFieldNumber = 3;
    private uint unCanFetchInfo_;
    /// <summary>
    /// 可以领取的档次,二进制位表示
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnCanFetchInfo {
      get { return unCanFetchInfo_; }
      set {
        unCanFetchInfo_ = value;
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private uint unErrorCode_;
    /// <summary>
    /// 返回错误码 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeConsumerQueryInfoS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeConsumerQueryInfoS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UllMoneyTotal != other.UllMoneyTotal) return false;
      if (UnFetchInfo != other.UnFetchInfo) return false;
      if (UnCanFetchInfo != other.UnCanFetchInfo) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UllMoneyTotal != 0UL) hash ^= UllMoneyTotal.GetHashCode();
      if (UnFetchInfo != 0) hash ^= UnFetchInfo.GetHashCode();
      if (UnCanFetchInfo != 0) hash ^= UnCanFetchInfo.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UllMoneyTotal != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(UllMoneyTotal);
      }
      if (UnFetchInfo != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(UnFetchInfo);
      }
      if (UnCanFetchInfo != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(UnCanFetchInfo);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteUInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UllMoneyTotal != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UllMoneyTotal);
      }
      if (UnFetchInfo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnFetchInfo);
      }
      if (UnCanFetchInfo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnCanFetchInfo);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeConsumerQueryInfoS other) {
      if (other == null) {
        return;
      }
      if (other.UllMoneyTotal != 0UL) {
        UllMoneyTotal = other.UllMoneyTotal;
      }
      if (other.UnFetchInfo != 0) {
        UnFetchInfo = other.UnFetchInfo;
      }
      if (other.UnCanFetchInfo != 0) {
        UnCanFetchInfo = other.UnCanFetchInfo;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UllMoneyTotal = input.ReadUInt64();
            break;
          }
          case 16: {
            UnFetchInfo = input.ReadUInt32();
            break;
          }
          case 24: {
            UnCanFetchInfo = input.ReadUInt32();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务端：通知客户端哪些档次可以领取奖励了
  /// _MSG_RECHARGE_CONSUMER_SYN_CAN_FETCH_S
  /// </summary>
  public sealed partial class PMsgRechargeConsumerSynCanFetchS : pb::IMessage<PMsgRechargeConsumerSynCanFetchS> {
    private static readonly pb::MessageParser<PMsgRechargeConsumerSynCanFetchS> _parser = new pb::MessageParser<PMsgRechargeConsumerSynCanFetchS>(() => new PMsgRechargeConsumerSynCanFetchS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeConsumerSynCanFetchS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeConsumerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerSynCanFetchS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerSynCanFetchS(PMsgRechargeConsumerSynCanFetchS other) : this() {
      unCanFetchInfo_ = other.unCanFetchInfo_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerSynCanFetchS Clone() {
      return new PMsgRechargeConsumerSynCanFetchS(this);
    }

    /// <summary>Field number for the "unCanFetchInfo" field.</summary>
    public const int UnCanFetchInfoFieldNumber = 1;
    private uint unCanFetchInfo_;
    /// <summary>
    /// 可以领取的档次,二进制位表示
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnCanFetchInfo {
      get { return unCanFetchInfo_; }
      set {
        unCanFetchInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeConsumerSynCanFetchS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeConsumerSynCanFetchS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnCanFetchInfo != other.UnCanFetchInfo) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnCanFetchInfo != 0) hash ^= UnCanFetchInfo.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnCanFetchInfo != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UnCanFetchInfo);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnCanFetchInfo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnCanFetchInfo);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeConsumerSynCanFetchS other) {
      if (other == null) {
        return;
      }
      if (other.UnCanFetchInfo != 0) {
        UnCanFetchInfo = other.UnCanFetchInfo;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnCanFetchInfo = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端：领取奖励
  /// _MSG_RECHARGE_CONSUMER_FETCH_REWARD_C
  /// </summary>
  public sealed partial class PMsgRechargeConsumerFetchRewardC : pb::IMessage<PMsgRechargeConsumerFetchRewardC> {
    private static readonly pb::MessageParser<PMsgRechargeConsumerFetchRewardC> _parser = new pb::MessageParser<PMsgRechargeConsumerFetchRewardC>(() => new PMsgRechargeConsumerFetchRewardC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeConsumerFetchRewardC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeConsumerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerFetchRewardC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerFetchRewardC(PMsgRechargeConsumerFetchRewardC other) : this() {
      unFetchLevel_ = other.unFetchLevel_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerFetchRewardC Clone() {
      return new PMsgRechargeConsumerFetchRewardC(this);
    }

    /// <summary>Field number for the "unFetchLevel" field.</summary>
    public const int UnFetchLevelFieldNumber = 1;
    private uint unFetchLevel_;
    /// <summary>
    /// 领取第几个档次的奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnFetchLevel {
      get { return unFetchLevel_; }
      set {
        unFetchLevel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeConsumerFetchRewardC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeConsumerFetchRewardC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnFetchLevel != other.UnFetchLevel) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnFetchLevel != 0) hash ^= UnFetchLevel.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnFetchLevel != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UnFetchLevel);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnFetchLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnFetchLevel);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeConsumerFetchRewardC other) {
      if (other == null) {
        return;
      }
      if (other.UnFetchLevel != 0) {
        UnFetchLevel = other.UnFetchLevel;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnFetchLevel = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务端：领取奖励回复
  /// _MSG_RECHARGE_CONSUMER_FETCH_REWARD_S
  /// </summary>
  public sealed partial class PMsgRechargeConsumerFetchRewardS : pb::IMessage<PMsgRechargeConsumerFetchRewardS> {
    private static readonly pb::MessageParser<PMsgRechargeConsumerFetchRewardS> _parser = new pb::MessageParser<PMsgRechargeConsumerFetchRewardS>(() => new PMsgRechargeConsumerFetchRewardS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeConsumerFetchRewardS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeConsumerReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerFetchRewardS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerFetchRewardS(PMsgRechargeConsumerFetchRewardS other) : this() {
      ullMoneyTotal_ = other.ullMoneyTotal_;
      unFetchInfo_ = other.unFetchInfo_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeConsumerFetchRewardS Clone() {
      return new PMsgRechargeConsumerFetchRewardS(this);
    }

    /// <summary>Field number for the "ullMoneyTotal" field.</summary>
    public const int UllMoneyTotalFieldNumber = 1;
    private ulong ullMoneyTotal_;
    /// <summary>
    /// 充值消费金额累积数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UllMoneyTotal {
      get { return ullMoneyTotal_; }
      set {
        ullMoneyTotal_ = value;
      }
    }

    /// <summary>Field number for the "unFetchInfo" field.</summary>
    public const int UnFetchInfoFieldNumber = 2;
    private uint unFetchInfo_;
    /// <summary>
    /// 领取累积充值奖励情况,二进制位表示
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnFetchInfo {
      get { return unFetchInfo_; }
      set {
        unFetchInfo_ = value;
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private uint unErrorCode_;
    /// <summary>
    /// 返回错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeConsumerFetchRewardS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeConsumerFetchRewardS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UllMoneyTotal != other.UllMoneyTotal) return false;
      if (UnFetchInfo != other.UnFetchInfo) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UllMoneyTotal != 0UL) hash ^= UllMoneyTotal.GetHashCode();
      if (UnFetchInfo != 0) hash ^= UnFetchInfo.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UllMoneyTotal != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(UllMoneyTotal);
      }
      if (UnFetchInfo != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(UnFetchInfo);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteUInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UllMoneyTotal != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UllMoneyTotal);
      }
      if (UnFetchInfo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UnFetchInfo);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeConsumerFetchRewardS other) {
      if (other == null) {
        return;
      }
      if (other.UllMoneyTotal != 0UL) {
        UllMoneyTotal = other.UllMoneyTotal;
      }
      if (other.UnFetchInfo != 0) {
        UnFetchInfo = other.UnFetchInfo;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UllMoneyTotal = input.ReadUInt64();
            break;
          }
          case 16: {
            UnFetchInfo = input.ReadUInt32();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
