// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/PMsgRecharge.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sw {

  /// <summary>Holder for reflection information generated from protos/PMsgRecharge.proto</summary>
  public static partial class PMsgRechargeReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/PMsgRecharge.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PMsgRechargeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chlwcm90b3MvUE1zZ1JlY2hhcmdlLnByb3RvEgJzdyIsChZQTXNnUmVjaGFy",
            "Z2VHb29kc0luZm9DEhIKCnVuUmVzZXJ2ZWQYASABKAUixgEKEVJlY2hhcmdl",
            "R29vZHNJbmZvEgwKBHVuSWQYASABKAUSDwoHdW5QcmljZRgCIAEoBRINCgV1",
            "bkdlbRgDIAEoBRISCgp1bkV4dHJhR2VtGAQgASgFEhMKC3VuRXh0cmFUaW1l",
            "GAUgASgFEhoKEnVuQ3VycmVudEV4dHJhVGltZRgGIAEoBRIVCg11bGxTYWxl",
            "c1N0YXJ0GAcgASgDEhMKC3VsbFNhbGVzRW5kGAggASgDEhIKCnVuU2FsZXNH",
            "ZW0YCSABKAUiTwoWUE1zZ1JlY2hhcmdlR29vZHNJbmZvUxIPCgd1bkNvdW50",
            "GAEgASgFEiQKBWNJbmZvGAIgAygLMhUuc3cuUmVjaGFyZ2VHb29kc0luZm8i",
            "bgoVUE1zZ1JlY2hhcmdlTmV3T3JkZXJDEhYKDnVuUGxhdGZvcm1UeXBlGAEg",
            "ASgFEhMKC3VuQ2hhbm5lbElkGAIgASgFEhEKCXVuR29vZHNJZBgDIAEoBRIV",
            "Cg1zekNoYW5uZWxEYXRhGAQgASgJImkKFVBNc2dSZWNoYXJnZU5ld09yZGVy",
            "UxIRCgl1bkdvb2RzSWQYASABKAUSFQoNc3pDaGFubmVsRGF0YRgCIAEoCRIR",
            "Cglzek9yZGVySWQYAyABKAkSEwoLdW5FcnJvckNvZGUYYyABKAUiLQoYUE1z",
            "Z1JlY2hhcmdlQ2FuY2VsT3JkZXJDEhEKCXN6T3JkZXJJZBgBIAEoCSJCChhQ",
            "TXNnUmVjaGFyZ2VDYW5jZWxPcmRlclMSEQoJc3pPcmRlcklkGAEgASgJEhMK",
            "C3VuRXJyb3JDb2RlGGMgASgFIiwKF1BNc2dSZWNoYXJnZVBheVN1Y2Nlc3ND",
            "EhEKCXN6T3JkZXJJZBgBIAEoCSJBChdQTXNnUmVjaGFyZ2VQYXlTdWNjZXNz",
            "UxIRCglzek9yZGVySWQYASABKAkSEwoLdW5FcnJvckNvZGUYYyABKAUiXgoS",
            "UE1zZ1JlY2hhcmdlQXdhcmRTEhEKCXN6T3JkZXJJZBgBIAEoCRINCgV1bkdl",
            "bRgCIAEoBRISCgp1bkV4dHJhR2VtGAMgASgFEhIKCnVuU2FsZXNHZW0YBCAB",
            "KAUiTQodUE1zZ0dvb2dsZVJlY2hhcmdlUGF5U3VjY2Vzc0MSEwoLc3pQcm9k",
            "dWN0SWQYASABKAkSFwoPc3pQdXJjaGFzZVRva2VuGAIgASgJImIKHVBNc2dH",
            "b29nbGVSZWNoYXJnZVBheVN1Y2Nlc3NTEhMKC3N6UHJvZHVjdElkGAEgASgJ",
            "EhcKD3N6UHVyY2hhc2VUb2tlbhgCIAEoCRITCgt1bkVycm9yQ29kZRhjIAEo",
            "BWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeGoodsInfoC), global::Sw.PMsgRechargeGoodsInfoC.Parser, new[]{ "UnReserved" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.RechargeGoodsInfo), global::Sw.RechargeGoodsInfo.Parser, new[]{ "UnId", "UnPrice", "UnGem", "UnExtraGem", "UnExtraTime", "UnCurrentExtraTime", "UllSalesStart", "UllSalesEnd", "UnSalesGem" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeGoodsInfoS), global::Sw.PMsgRechargeGoodsInfoS.Parser, new[]{ "UnCount", "CInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeNewOrderC), global::Sw.PMsgRechargeNewOrderC.Parser, new[]{ "UnPlatformType", "UnChannelId", "UnGoodsId", "SzChannelData" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeNewOrderS), global::Sw.PMsgRechargeNewOrderS.Parser, new[]{ "UnGoodsId", "SzChannelData", "SzOrderId", "UnErrorCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeCancelOrderC), global::Sw.PMsgRechargeCancelOrderC.Parser, new[]{ "SzOrderId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeCancelOrderS), global::Sw.PMsgRechargeCancelOrderS.Parser, new[]{ "SzOrderId", "UnErrorCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargePaySuccessC), global::Sw.PMsgRechargePaySuccessC.Parser, new[]{ "SzOrderId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargePaySuccessS), global::Sw.PMsgRechargePaySuccessS.Parser, new[]{ "SzOrderId", "UnErrorCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgRechargeAwardS), global::Sw.PMsgRechargeAwardS.Parser, new[]{ "SzOrderId", "UnGem", "UnExtraGem", "UnSalesGem" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgGoogleRechargePaySuccessC), global::Sw.PMsgGoogleRechargePaySuccessC.Parser, new[]{ "SzProductId", "SzPurchaseToken" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Sw.PMsgGoogleRechargePaySuccessS), global::Sw.PMsgGoogleRechargePaySuccessS.Parser, new[]{ "SzProductId", "SzPurchaseToken", "UnErrorCode" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 客户端：请求商品信息
  /// _MSG_RECHARGE_GOODS_INFO_C
  /// </summary>
  public sealed partial class PMsgRechargeGoodsInfoC : pb::IMessage<PMsgRechargeGoodsInfoC> {
    private static readonly pb::MessageParser<PMsgRechargeGoodsInfoC> _parser = new pb::MessageParser<PMsgRechargeGoodsInfoC>(() => new PMsgRechargeGoodsInfoC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeGoodsInfoC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeGoodsInfoC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeGoodsInfoC(PMsgRechargeGoodsInfoC other) : this() {
      unReserved_ = other.unReserved_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeGoodsInfoC Clone() {
      return new PMsgRechargeGoodsInfoC(this);
    }

    /// <summary>Field number for the "unReserved" field.</summary>
    public const int UnReservedFieldNumber = 1;
    private int unReserved_;
    /// <summary>
    /// 保留字段
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnReserved {
      get { return unReserved_; }
      set {
        unReserved_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeGoodsInfoC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeGoodsInfoC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnReserved != other.UnReserved) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnReserved != 0) hash ^= UnReserved.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnReserved != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnReserved);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnReserved != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnReserved);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeGoodsInfoC other) {
      if (other == null) {
        return;
      }
      if (other.UnReserved != 0) {
        UnReserved = other.UnReserved;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnReserved = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 商品信息
  /// </summary>
  public sealed partial class RechargeGoodsInfo : pb::IMessage<RechargeGoodsInfo> {
    private static readonly pb::MessageParser<RechargeGoodsInfo> _parser = new pb::MessageParser<RechargeGoodsInfo>(() => new RechargeGoodsInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RechargeGoodsInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RechargeGoodsInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RechargeGoodsInfo(RechargeGoodsInfo other) : this() {
      unId_ = other.unId_;
      unPrice_ = other.unPrice_;
      unGem_ = other.unGem_;
      unExtraGem_ = other.unExtraGem_;
      unExtraTime_ = other.unExtraTime_;
      unCurrentExtraTime_ = other.unCurrentExtraTime_;
      ullSalesStart_ = other.ullSalesStart_;
      ullSalesEnd_ = other.ullSalesEnd_;
      unSalesGem_ = other.unSalesGem_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RechargeGoodsInfo Clone() {
      return new RechargeGoodsInfo(this);
    }

    /// <summary>Field number for the "unId" field.</summary>
    public const int UnIdFieldNumber = 1;
    private int unId_;
    /// <summary>
    /// 装备id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnId {
      get { return unId_; }
      set {
        unId_ = value;
      }
    }

    /// <summary>Field number for the "unPrice" field.</summary>
    public const int UnPriceFieldNumber = 2;
    private int unPrice_;
    /// <summary>
    /// 价格（分）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnPrice {
      get { return unPrice_; }
      set {
        unPrice_ = value;
      }
    }

    /// <summary>Field number for the "unGem" field.</summary>
    public const int UnGemFieldNumber = 3;
    private int unGem_;
    /// <summary>
    /// 充值元宝
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnGem {
      get { return unGem_; }
      set {
        unGem_ = value;
      }
    }

    /// <summary>Field number for the "unExtraGem" field.</summary>
    public const int UnExtraGemFieldNumber = 4;
    private int unExtraGem_;
    /// <summary>
    /// 赠送元宝
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnExtraGem {
      get { return unExtraGem_; }
      set {
        unExtraGem_ = value;
      }
    }

    /// <summary>Field number for the "unExtraTime" field.</summary>
    public const int UnExtraTimeFieldNumber = 5;
    private int unExtraTime_;
    /// <summary>
    /// 赠送次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnExtraTime {
      get { return unExtraTime_; }
      set {
        unExtraTime_ = value;
      }
    }

    /// <summary>Field number for the "unCurrentExtraTime" field.</summary>
    public const int UnCurrentExtraTimeFieldNumber = 6;
    private int unCurrentExtraTime_;
    /// <summary>
    /// 已赠送次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnCurrentExtraTime {
      get { return unCurrentExtraTime_; }
      set {
        unCurrentExtraTime_ = value;
      }
    }

    /// <summary>Field number for the "ullSalesStart" field.</summary>
    public const int UllSalesStartFieldNumber = 7;
    private long ullSalesStart_;
    /// <summary>
    /// 充值活动开始时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UllSalesStart {
      get { return ullSalesStart_; }
      set {
        ullSalesStart_ = value;
      }
    }

    /// <summary>Field number for the "ullSalesEnd" field.</summary>
    public const int UllSalesEndFieldNumber = 8;
    private long ullSalesEnd_;
    /// <summary>
    /// 充值活动结束时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UllSalesEnd {
      get { return ullSalesEnd_; }
      set {
        ullSalesEnd_ = value;
      }
    }

    /// <summary>Field number for the "unSalesGem" field.</summary>
    public const int UnSalesGemFieldNumber = 9;
    private int unSalesGem_;
    /// <summary>
    /// 充值活动赠送的元宝
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnSalesGem {
      get { return unSalesGem_; }
      set {
        unSalesGem_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RechargeGoodsInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RechargeGoodsInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnId != other.UnId) return false;
      if (UnPrice != other.UnPrice) return false;
      if (UnGem != other.UnGem) return false;
      if (UnExtraGem != other.UnExtraGem) return false;
      if (UnExtraTime != other.UnExtraTime) return false;
      if (UnCurrentExtraTime != other.UnCurrentExtraTime) return false;
      if (UllSalesStart != other.UllSalesStart) return false;
      if (UllSalesEnd != other.UllSalesEnd) return false;
      if (UnSalesGem != other.UnSalesGem) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnId != 0) hash ^= UnId.GetHashCode();
      if (UnPrice != 0) hash ^= UnPrice.GetHashCode();
      if (UnGem != 0) hash ^= UnGem.GetHashCode();
      if (UnExtraGem != 0) hash ^= UnExtraGem.GetHashCode();
      if (UnExtraTime != 0) hash ^= UnExtraTime.GetHashCode();
      if (UnCurrentExtraTime != 0) hash ^= UnCurrentExtraTime.GetHashCode();
      if (UllSalesStart != 0L) hash ^= UllSalesStart.GetHashCode();
      if (UllSalesEnd != 0L) hash ^= UllSalesEnd.GetHashCode();
      if (UnSalesGem != 0) hash ^= UnSalesGem.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnId);
      }
      if (UnPrice != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnPrice);
      }
      if (UnGem != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(UnGem);
      }
      if (UnExtraGem != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(UnExtraGem);
      }
      if (UnExtraTime != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(UnExtraTime);
      }
      if (UnCurrentExtraTime != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(UnCurrentExtraTime);
      }
      if (UllSalesStart != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(UllSalesStart);
      }
      if (UllSalesEnd != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(UllSalesEnd);
      }
      if (UnSalesGem != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(UnSalesGem);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnId);
      }
      if (UnPrice != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnPrice);
      }
      if (UnGem != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnGem);
      }
      if (UnExtraGem != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnExtraGem);
      }
      if (UnExtraTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnExtraTime);
      }
      if (UnCurrentExtraTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnCurrentExtraTime);
      }
      if (UllSalesStart != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UllSalesStart);
      }
      if (UllSalesEnd != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UllSalesEnd);
      }
      if (UnSalesGem != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnSalesGem);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RechargeGoodsInfo other) {
      if (other == null) {
        return;
      }
      if (other.UnId != 0) {
        UnId = other.UnId;
      }
      if (other.UnPrice != 0) {
        UnPrice = other.UnPrice;
      }
      if (other.UnGem != 0) {
        UnGem = other.UnGem;
      }
      if (other.UnExtraGem != 0) {
        UnExtraGem = other.UnExtraGem;
      }
      if (other.UnExtraTime != 0) {
        UnExtraTime = other.UnExtraTime;
      }
      if (other.UnCurrentExtraTime != 0) {
        UnCurrentExtraTime = other.UnCurrentExtraTime;
      }
      if (other.UllSalesStart != 0L) {
        UllSalesStart = other.UllSalesStart;
      }
      if (other.UllSalesEnd != 0L) {
        UllSalesEnd = other.UllSalesEnd;
      }
      if (other.UnSalesGem != 0) {
        UnSalesGem = other.UnSalesGem;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnId = input.ReadInt32();
            break;
          }
          case 16: {
            UnPrice = input.ReadInt32();
            break;
          }
          case 24: {
            UnGem = input.ReadInt32();
            break;
          }
          case 32: {
            UnExtraGem = input.ReadInt32();
            break;
          }
          case 40: {
            UnExtraTime = input.ReadInt32();
            break;
          }
          case 48: {
            UnCurrentExtraTime = input.ReadInt32();
            break;
          }
          case 56: {
            UllSalesStart = input.ReadInt64();
            break;
          }
          case 64: {
            UllSalesEnd = input.ReadInt64();
            break;
          }
          case 72: {
            UnSalesGem = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：请求商品信息回复
  /// _MSG_RECHARGE_GOODS_INFO_S
  /// </summary>
  public sealed partial class PMsgRechargeGoodsInfoS : pb::IMessage<PMsgRechargeGoodsInfoS> {
    private static readonly pb::MessageParser<PMsgRechargeGoodsInfoS> _parser = new pb::MessageParser<PMsgRechargeGoodsInfoS>(() => new PMsgRechargeGoodsInfoS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeGoodsInfoS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeGoodsInfoS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeGoodsInfoS(PMsgRechargeGoodsInfoS other) : this() {
      unCount_ = other.unCount_;
      cInfo_ = other.cInfo_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeGoodsInfoS Clone() {
      return new PMsgRechargeGoodsInfoS(this);
    }

    /// <summary>Field number for the "unCount" field.</summary>
    public const int UnCountFieldNumber = 1;
    private int unCount_;
    /// <summary>
    /// 商品数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnCount {
      get { return unCount_; }
      set {
        unCount_ = value;
      }
    }

    /// <summary>Field number for the "cInfo" field.</summary>
    public const int CInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Sw.RechargeGoodsInfo> _repeated_cInfo_codec
        = pb::FieldCodec.ForMessage(18, global::Sw.RechargeGoodsInfo.Parser);
    private readonly pbc::RepeatedField<global::Sw.RechargeGoodsInfo> cInfo_ = new pbc::RepeatedField<global::Sw.RechargeGoodsInfo>();
    /// <summary>
    /// 商品信息列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Sw.RechargeGoodsInfo> CInfo {
      get { return cInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeGoodsInfoS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeGoodsInfoS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnCount != other.UnCount) return false;
      if(!cInfo_.Equals(other.cInfo_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnCount != 0) hash ^= UnCount.GetHashCode();
      hash ^= cInfo_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnCount);
      }
      cInfo_.WriteTo(output, _repeated_cInfo_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnCount);
      }
      size += cInfo_.CalculateSize(_repeated_cInfo_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeGoodsInfoS other) {
      if (other == null) {
        return;
      }
      if (other.UnCount != 0) {
        UnCount = other.UnCount;
      }
      cInfo_.Add(other.cInfo_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnCount = input.ReadInt32();
            break;
          }
          case 18: {
            cInfo_.AddEntriesFrom(input, _repeated_cInfo_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端：请求创建新的充值订单
  /// _MSG_RECHARGE_NEW_ORDER_C
  /// </summary>
  public sealed partial class PMsgRechargeNewOrderC : pb::IMessage<PMsgRechargeNewOrderC> {
    private static readonly pb::MessageParser<PMsgRechargeNewOrderC> _parser = new pb::MessageParser<PMsgRechargeNewOrderC>(() => new PMsgRechargeNewOrderC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeNewOrderC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeNewOrderC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeNewOrderC(PMsgRechargeNewOrderC other) : this() {
      unPlatformType_ = other.unPlatformType_;
      unChannelId_ = other.unChannelId_;
      unGoodsId_ = other.unGoodsId_;
      szChannelData_ = other.szChannelData_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeNewOrderC Clone() {
      return new PMsgRechargeNewOrderC(this);
    }

    /// <summary>Field number for the "unPlatformType" field.</summary>
    public const int UnPlatformTypeFieldNumber = 1;
    private int unPlatformType_;
    /// <summary>
    /// 平台类型（sw::PLATFORM_TYPE）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnPlatformType {
      get { return unPlatformType_; }
      set {
        unPlatformType_ = value;
      }
    }

    /// <summary>Field number for the "unChannelId" field.</summary>
    public const int UnChannelIdFieldNumber = 2;
    private int unChannelId_;
    /// <summary>
    /// 渠道类型（sw::CHANNEL_TYPE）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnChannelId {
      get { return unChannelId_; }
      set {
        unChannelId_ = value;
      }
    }

    /// <summary>Field number for the "unGoodsId" field.</summary>
    public const int UnGoodsIdFieldNumber = 3;
    private int unGoodsId_;
    /// <summary>
    /// 商品id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnGoodsId {
      get { return unGoodsId_; }
      set {
        unGoodsId_ = value;
      }
    }

    /// <summary>Field number for the "szChannelData" field.</summary>
    public const int SzChannelDataFieldNumber = 4;
    private string szChannelData_ = "";
    /// <summary>
    /// 附加信息，根据渠道不同含义不同
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzChannelData {
      get { return szChannelData_; }
      set {
        szChannelData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeNewOrderC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeNewOrderC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnPlatformType != other.UnPlatformType) return false;
      if (UnChannelId != other.UnChannelId) return false;
      if (UnGoodsId != other.UnGoodsId) return false;
      if (SzChannelData != other.SzChannelData) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnPlatformType != 0) hash ^= UnPlatformType.GetHashCode();
      if (UnChannelId != 0) hash ^= UnChannelId.GetHashCode();
      if (UnGoodsId != 0) hash ^= UnGoodsId.GetHashCode();
      if (SzChannelData.Length != 0) hash ^= SzChannelData.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnPlatformType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnPlatformType);
      }
      if (UnChannelId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnChannelId);
      }
      if (UnGoodsId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(UnGoodsId);
      }
      if (SzChannelData.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SzChannelData);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnPlatformType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnPlatformType);
      }
      if (UnChannelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnChannelId);
      }
      if (UnGoodsId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnGoodsId);
      }
      if (SzChannelData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzChannelData);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeNewOrderC other) {
      if (other == null) {
        return;
      }
      if (other.UnPlatformType != 0) {
        UnPlatformType = other.UnPlatformType;
      }
      if (other.UnChannelId != 0) {
        UnChannelId = other.UnChannelId;
      }
      if (other.UnGoodsId != 0) {
        UnGoodsId = other.UnGoodsId;
      }
      if (other.SzChannelData.Length != 0) {
        SzChannelData = other.SzChannelData;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnPlatformType = input.ReadInt32();
            break;
          }
          case 16: {
            UnChannelId = input.ReadInt32();
            break;
          }
          case 24: {
            UnGoodsId = input.ReadInt32();
            break;
          }
          case 34: {
            SzChannelData = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：请求创建新的充值订单回复
  /// _MSG_RECHARGE_NEW_ORDER_S
  /// </summary>
  public sealed partial class PMsgRechargeNewOrderS : pb::IMessage<PMsgRechargeNewOrderS> {
    private static readonly pb::MessageParser<PMsgRechargeNewOrderS> _parser = new pb::MessageParser<PMsgRechargeNewOrderS>(() => new PMsgRechargeNewOrderS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeNewOrderS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeNewOrderS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeNewOrderS(PMsgRechargeNewOrderS other) : this() {
      unGoodsId_ = other.unGoodsId_;
      szChannelData_ = other.szChannelData_;
      szOrderId_ = other.szOrderId_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeNewOrderS Clone() {
      return new PMsgRechargeNewOrderS(this);
    }

    /// <summary>Field number for the "unGoodsId" field.</summary>
    public const int UnGoodsIdFieldNumber = 1;
    private int unGoodsId_;
    /// <summary>
    /// 商品id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnGoodsId {
      get { return unGoodsId_; }
      set {
        unGoodsId_ = value;
      }
    }

    /// <summary>Field number for the "szChannelData" field.</summary>
    public const int SzChannelDataFieldNumber = 2;
    private string szChannelData_ = "";
    /// <summary>
    /// 附加信息，根据渠道不同含义不同
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzChannelData {
      get { return szChannelData_; }
      set {
        szChannelData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "szOrderId" field.</summary>
    public const int SzOrderIdFieldNumber = 3;
    private string szOrderId_ = "";
    /// <summary>
    /// 订单id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzOrderId {
      get { return szOrderId_; }
      set {
        szOrderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private int unErrorCode_;
    /// <summary>
    /// 返回错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeNewOrderS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeNewOrderS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnGoodsId != other.UnGoodsId) return false;
      if (SzChannelData != other.SzChannelData) return false;
      if (SzOrderId != other.SzOrderId) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnGoodsId != 0) hash ^= UnGoodsId.GetHashCode();
      if (SzChannelData.Length != 0) hash ^= SzChannelData.GetHashCode();
      if (SzOrderId.Length != 0) hash ^= SzOrderId.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnGoodsId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UnGoodsId);
      }
      if (SzChannelData.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SzChannelData);
      }
      if (SzOrderId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SzOrderId);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnGoodsId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnGoodsId);
      }
      if (SzChannelData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzChannelData);
      }
      if (SzOrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzOrderId);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeNewOrderS other) {
      if (other == null) {
        return;
      }
      if (other.UnGoodsId != 0) {
        UnGoodsId = other.UnGoodsId;
      }
      if (other.SzChannelData.Length != 0) {
        SzChannelData = other.SzChannelData;
      }
      if (other.SzOrderId.Length != 0) {
        SzOrderId = other.SzOrderId;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UnGoodsId = input.ReadInt32();
            break;
          }
          case 18: {
            SzChannelData = input.ReadString();
            break;
          }
          case 26: {
            SzOrderId = input.ReadString();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端：请求取消充值订单
  /// _MSG_RECHARGE_CANCEL_ORDER_C
  /// </summary>
  public sealed partial class PMsgRechargeCancelOrderC : pb::IMessage<PMsgRechargeCancelOrderC> {
    private static readonly pb::MessageParser<PMsgRechargeCancelOrderC> _parser = new pb::MessageParser<PMsgRechargeCancelOrderC>(() => new PMsgRechargeCancelOrderC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeCancelOrderC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeCancelOrderC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeCancelOrderC(PMsgRechargeCancelOrderC other) : this() {
      szOrderId_ = other.szOrderId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeCancelOrderC Clone() {
      return new PMsgRechargeCancelOrderC(this);
    }

    /// <summary>Field number for the "szOrderId" field.</summary>
    public const int SzOrderIdFieldNumber = 1;
    private string szOrderId_ = "";
    /// <summary>
    /// 订单id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzOrderId {
      get { return szOrderId_; }
      set {
        szOrderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeCancelOrderC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeCancelOrderC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SzOrderId != other.SzOrderId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SzOrderId.Length != 0) hash ^= SzOrderId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SzOrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SzOrderId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SzOrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzOrderId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeCancelOrderC other) {
      if (other == null) {
        return;
      }
      if (other.SzOrderId.Length != 0) {
        SzOrderId = other.SzOrderId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            SzOrderId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：请求取消充值订单回复
  /// _MSG_RECHARGE_CANCEL_ORDER_S
  /// </summary>
  public sealed partial class PMsgRechargeCancelOrderS : pb::IMessage<PMsgRechargeCancelOrderS> {
    private static readonly pb::MessageParser<PMsgRechargeCancelOrderS> _parser = new pb::MessageParser<PMsgRechargeCancelOrderS>(() => new PMsgRechargeCancelOrderS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeCancelOrderS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeCancelOrderS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeCancelOrderS(PMsgRechargeCancelOrderS other) : this() {
      szOrderId_ = other.szOrderId_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeCancelOrderS Clone() {
      return new PMsgRechargeCancelOrderS(this);
    }

    /// <summary>Field number for the "szOrderId" field.</summary>
    public const int SzOrderIdFieldNumber = 1;
    private string szOrderId_ = "";
    /// <summary>
    /// 订单id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzOrderId {
      get { return szOrderId_; }
      set {
        szOrderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private int unErrorCode_;
    /// <summary>
    /// 返回错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeCancelOrderS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeCancelOrderS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SzOrderId != other.SzOrderId) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SzOrderId.Length != 0) hash ^= SzOrderId.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SzOrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SzOrderId);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SzOrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzOrderId);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeCancelOrderS other) {
      if (other == null) {
        return;
      }
      if (other.SzOrderId.Length != 0) {
        SzOrderId = other.SzOrderId;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            SzOrderId = input.ReadString();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端：订单完成支付
  /// _MSG_RECHARGE_PAY_SUCCESS_C
  /// </summary>
  public sealed partial class PMsgRechargePaySuccessC : pb::IMessage<PMsgRechargePaySuccessC> {
    private static readonly pb::MessageParser<PMsgRechargePaySuccessC> _parser = new pb::MessageParser<PMsgRechargePaySuccessC>(() => new PMsgRechargePaySuccessC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargePaySuccessC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargePaySuccessC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargePaySuccessC(PMsgRechargePaySuccessC other) : this() {
      szOrderId_ = other.szOrderId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargePaySuccessC Clone() {
      return new PMsgRechargePaySuccessC(this);
    }

    /// <summary>Field number for the "szOrderId" field.</summary>
    public const int SzOrderIdFieldNumber = 1;
    private string szOrderId_ = "";
    /// <summary>
    /// 订单id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzOrderId {
      get { return szOrderId_; }
      set {
        szOrderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargePaySuccessC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargePaySuccessC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SzOrderId != other.SzOrderId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SzOrderId.Length != 0) hash ^= SzOrderId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SzOrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SzOrderId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SzOrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzOrderId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargePaySuccessC other) {
      if (other == null) {
        return;
      }
      if (other.SzOrderId.Length != 0) {
        SzOrderId = other.SzOrderId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            SzOrderId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：订单完成支付回复
  /// _MSG_RECHARGE_PAY_SUCCESS_S
  /// </summary>
  public sealed partial class PMsgRechargePaySuccessS : pb::IMessage<PMsgRechargePaySuccessS> {
    private static readonly pb::MessageParser<PMsgRechargePaySuccessS> _parser = new pb::MessageParser<PMsgRechargePaySuccessS>(() => new PMsgRechargePaySuccessS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargePaySuccessS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargePaySuccessS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargePaySuccessS(PMsgRechargePaySuccessS other) : this() {
      szOrderId_ = other.szOrderId_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargePaySuccessS Clone() {
      return new PMsgRechargePaySuccessS(this);
    }

    /// <summary>Field number for the "szOrderId" field.</summary>
    public const int SzOrderIdFieldNumber = 1;
    private string szOrderId_ = "";
    /// <summary>
    /// 订单id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzOrderId {
      get { return szOrderId_; }
      set {
        szOrderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private int unErrorCode_;
    /// <summary>
    /// 返回错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargePaySuccessS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargePaySuccessS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SzOrderId != other.SzOrderId) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SzOrderId.Length != 0) hash ^= SzOrderId.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SzOrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SzOrderId);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SzOrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzOrderId);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargePaySuccessS other) {
      if (other == null) {
        return;
      }
      if (other.SzOrderId.Length != 0) {
        SzOrderId = other.SzOrderId;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            SzOrderId = input.ReadString();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：获得充值物品通知
  /// _MSG_RECHARGE_AWARD_S
  /// </summary>
  public sealed partial class PMsgRechargeAwardS : pb::IMessage<PMsgRechargeAwardS> {
    private static readonly pb::MessageParser<PMsgRechargeAwardS> _parser = new pb::MessageParser<PMsgRechargeAwardS>(() => new PMsgRechargeAwardS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgRechargeAwardS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeAwardS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeAwardS(PMsgRechargeAwardS other) : this() {
      szOrderId_ = other.szOrderId_;
      unGem_ = other.unGem_;
      unExtraGem_ = other.unExtraGem_;
      unSalesGem_ = other.unSalesGem_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgRechargeAwardS Clone() {
      return new PMsgRechargeAwardS(this);
    }

    /// <summary>Field number for the "szOrderId" field.</summary>
    public const int SzOrderIdFieldNumber = 1;
    private string szOrderId_ = "";
    /// <summary>
    /// 订单id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzOrderId {
      get { return szOrderId_; }
      set {
        szOrderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unGem" field.</summary>
    public const int UnGemFieldNumber = 2;
    private int unGem_;
    /// <summary>
    /// 充值获得元宝
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnGem {
      get { return unGem_; }
      set {
        unGem_ = value;
      }
    }

    /// <summary>Field number for the "unExtraGem" field.</summary>
    public const int UnExtraGemFieldNumber = 3;
    private int unExtraGem_;
    /// <summary>
    /// 赠送元宝
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnExtraGem {
      get { return unExtraGem_; }
      set {
        unExtraGem_ = value;
      }
    }

    /// <summary>Field number for the "unSalesGem" field.</summary>
    public const int UnSalesGemFieldNumber = 4;
    private int unSalesGem_;
    /// <summary>
    /// 充值活动赠送的元宝
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnSalesGem {
      get { return unSalesGem_; }
      set {
        unSalesGem_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgRechargeAwardS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgRechargeAwardS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SzOrderId != other.SzOrderId) return false;
      if (UnGem != other.UnGem) return false;
      if (UnExtraGem != other.UnExtraGem) return false;
      if (UnSalesGem != other.UnSalesGem) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SzOrderId.Length != 0) hash ^= SzOrderId.GetHashCode();
      if (UnGem != 0) hash ^= UnGem.GetHashCode();
      if (UnExtraGem != 0) hash ^= UnExtraGem.GetHashCode();
      if (UnSalesGem != 0) hash ^= UnSalesGem.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SzOrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SzOrderId);
      }
      if (UnGem != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnGem);
      }
      if (UnExtraGem != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(UnExtraGem);
      }
      if (UnSalesGem != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(UnSalesGem);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SzOrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzOrderId);
      }
      if (UnGem != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnGem);
      }
      if (UnExtraGem != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnExtraGem);
      }
      if (UnSalesGem != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnSalesGem);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgRechargeAwardS other) {
      if (other == null) {
        return;
      }
      if (other.SzOrderId.Length != 0) {
        SzOrderId = other.SzOrderId;
      }
      if (other.UnGem != 0) {
        UnGem = other.UnGem;
      }
      if (other.UnExtraGem != 0) {
        UnExtraGem = other.UnExtraGem;
      }
      if (other.UnSalesGem != 0) {
        UnSalesGem = other.UnSalesGem;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            SzOrderId = input.ReadString();
            break;
          }
          case 16: {
            UnGem = input.ReadInt32();
            break;
          }
          case 24: {
            UnExtraGem = input.ReadInt32();
            break;
          }
          case 32: {
            UnSalesGem = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端：谷歌订单完成支付
  /// _MSG_GOOGLE_RECHARGE_PAY_SUCCESS_C
  /// </summary>
  public sealed partial class PMsgGoogleRechargePaySuccessC : pb::IMessage<PMsgGoogleRechargePaySuccessC> {
    private static readonly pb::MessageParser<PMsgGoogleRechargePaySuccessC> _parser = new pb::MessageParser<PMsgGoogleRechargePaySuccessC>(() => new PMsgGoogleRechargePaySuccessC());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgGoogleRechargePaySuccessC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgGoogleRechargePaySuccessC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgGoogleRechargePaySuccessC(PMsgGoogleRechargePaySuccessC other) : this() {
      szProductId_ = other.szProductId_;
      szPurchaseToken_ = other.szPurchaseToken_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgGoogleRechargePaySuccessC Clone() {
      return new PMsgGoogleRechargePaySuccessC(this);
    }

    /// <summary>Field number for the "szProductId" field.</summary>
    public const int SzProductIdFieldNumber = 1;
    private string szProductId_ = "";
    /// <summary>
    /// 商品id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzProductId {
      get { return szProductId_; }
      set {
        szProductId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "szPurchaseToken" field.</summary>
    public const int SzPurchaseTokenFieldNumber = 2;
    private string szPurchaseToken_ = "";
    /// <summary>
    /// 订单Token
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzPurchaseToken {
      get { return szPurchaseToken_; }
      set {
        szPurchaseToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgGoogleRechargePaySuccessC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgGoogleRechargePaySuccessC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SzProductId != other.SzProductId) return false;
      if (SzPurchaseToken != other.SzPurchaseToken) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SzProductId.Length != 0) hash ^= SzProductId.GetHashCode();
      if (SzPurchaseToken.Length != 0) hash ^= SzPurchaseToken.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SzProductId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SzProductId);
      }
      if (SzPurchaseToken.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SzPurchaseToken);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SzProductId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzProductId);
      }
      if (SzPurchaseToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzPurchaseToken);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgGoogleRechargePaySuccessC other) {
      if (other == null) {
        return;
      }
      if (other.SzProductId.Length != 0) {
        SzProductId = other.SzProductId;
      }
      if (other.SzPurchaseToken.Length != 0) {
        SzPurchaseToken = other.SzPurchaseToken;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            SzProductId = input.ReadString();
            break;
          }
          case 18: {
            SzPurchaseToken = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器：谷歌订单完成支付回复
  /// _MSG_GOOGLE_RECHARGE_PAY_SUCCESS_S
  /// </summary>
  public sealed partial class PMsgGoogleRechargePaySuccessS : pb::IMessage<PMsgGoogleRechargePaySuccessS> {
    private static readonly pb::MessageParser<PMsgGoogleRechargePaySuccessS> _parser = new pb::MessageParser<PMsgGoogleRechargePaySuccessS>(() => new PMsgGoogleRechargePaySuccessS());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PMsgGoogleRechargePaySuccessS> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sw.PMsgRechargeReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgGoogleRechargePaySuccessS() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgGoogleRechargePaySuccessS(PMsgGoogleRechargePaySuccessS other) : this() {
      szProductId_ = other.szProductId_;
      szPurchaseToken_ = other.szPurchaseToken_;
      unErrorCode_ = other.unErrorCode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PMsgGoogleRechargePaySuccessS Clone() {
      return new PMsgGoogleRechargePaySuccessS(this);
    }

    /// <summary>Field number for the "szProductId" field.</summary>
    public const int SzProductIdFieldNumber = 1;
    private string szProductId_ = "";
    /// <summary>
    /// 商品id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzProductId {
      get { return szProductId_; }
      set {
        szProductId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "szPurchaseToken" field.</summary>
    public const int SzPurchaseTokenFieldNumber = 2;
    private string szPurchaseToken_ = "";
    /// <summary>
    /// 订单Token
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SzPurchaseToken {
      get { return szPurchaseToken_; }
      set {
        szPurchaseToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unErrorCode" field.</summary>
    public const int UnErrorCodeFieldNumber = 99;
    private int unErrorCode_;
    /// <summary>
    /// 返回错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnErrorCode {
      get { return unErrorCode_; }
      set {
        unErrorCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PMsgGoogleRechargePaySuccessS);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PMsgGoogleRechargePaySuccessS other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SzProductId != other.SzProductId) return false;
      if (SzPurchaseToken != other.SzPurchaseToken) return false;
      if (UnErrorCode != other.UnErrorCode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SzProductId.Length != 0) hash ^= SzProductId.GetHashCode();
      if (SzPurchaseToken.Length != 0) hash ^= SzPurchaseToken.GetHashCode();
      if (UnErrorCode != 0) hash ^= UnErrorCode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SzProductId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SzProductId);
      }
      if (SzPurchaseToken.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SzPurchaseToken);
      }
      if (UnErrorCode != 0) {
        output.WriteRawTag(152, 6);
        output.WriteInt32(UnErrorCode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SzProductId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzProductId);
      }
      if (SzPurchaseToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SzPurchaseToken);
      }
      if (UnErrorCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(UnErrorCode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PMsgGoogleRechargePaySuccessS other) {
      if (other == null) {
        return;
      }
      if (other.SzProductId.Length != 0) {
        SzProductId = other.SzProductId;
      }
      if (other.SzPurchaseToken.Length != 0) {
        SzPurchaseToken = other.SzPurchaseToken;
      }
      if (other.UnErrorCode != 0) {
        UnErrorCode = other.UnErrorCode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            SzProductId = input.ReadString();
            break;
          }
          case 18: {
            SzPurchaseToken = input.ReadString();
            break;
          }
          case 792: {
            UnErrorCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
